### ISSUE TITLE
Support DI in controllers

### ISSUE THREAD

**Issue by jhuntoo** [pleerock/routing-controllers#10]
Hi, this a great library, I had actually rolled my own similar implementation using decorators but this is much more complete solution so I'm looking at migrating to routing-controllers.

My first thought is how canI I inject dependencies into controllers, would you be open to using a DI framework like https://github.com/inversify/InversifyJS/ ??

**Comment by pleerock** [comment]
Hi, there is a support of di containers already. Here is example with [typedi](https://github.com/pleerock/typedi):

```typescript
import {useContainer} from "routing-controllers";
import {Container} from "typedi";

useContainer(Container);
```

**useContainer** expects container signature with get method. Same technic can be applied to inversifyjs

**Comment by jhuntoo** [comment]
Awesome!

Does typedi do anything different/better than inversifyjs ?

**Comment by pleerock** [comment]
its simple and does everything di container should do. I have created it over a year ago, and successfully using it in production since that. choice of yours, but you can give a try to typedi, and if you are missing features there feel free to open an issue or contribute
