### ISSUE TITLE
Is there any way to pass socket.io instance to the routing-controller?

### ISSUE THREAD

**Issue by stonecold123** [pleerock/routing-controllers#100]
I found the common way to pass io instance to express routes is this:

./routes/routes.js
````
module.exports = function(app, io) {
  app.post('/cmp', function(req, res){
    var product_id = req.body.product_id;
    var bid = req.body.bid.split('b')[1];       

    io.sockets.emit("bidSuccess", {product_id: product_id, bid: bid});
    response.json(200, {message: "Message received!"});    
  })
};
````
app.js
````
var routes = require('./routes/routes');
routes(app, io);
````
But how can I do the same in routing controller?

Should I pass the socket instance via a middleware in app.js?
````
app.use((req, res, next) => {
  res.io = io
  next()
})
```
Any suggestions?

**Comment by pleerock** [comment]
you can use `socket-controllers` module, or you can create a custom param decorator, see more info [here](https://github.com/pleerock/routing-controllers/issues/75)
