### ISSUE TITLE
Is there any way to use optional params?

### ISSUE THREAD

**Issue by weldermarcosxd** [pleerock/routing-controllers#104]
Hi,

great work by the way. I'm using your work to rebuild an existing API that is in java now. At the moment they are using GET method url params like this: url?param=123?param2=321.
Is there any way to archive this with routing-controllers with express ?

I was able to do it with : url/param/param2 but thats would cost the refactoring of the app  too.

Thanks in advance!
Best Regards,
Welder Marcos

**Comment by weldermarcosxd** [comment]
Forget about it.

Found my solution with the @Req and @Res. Here is an example if someone else face this problem:

@Get("/post")
    findList (@Req() req: any, @Res() res: any) {
        res.send(req.query.param);
    }

**Comment by pleerock** [comment]
wait you can use `@QueryParam("paramName") paramName` decorator:

```ts
@Get("/post")
findList (@QueryParam("sortBy") sortBy: string) {
   return [];
}
```

**Comment by pleerock** [comment]
Closing this. Let me know if need anything else.

**Comment by weldermarcosxd** [comment]
Was a silly mistake, your solution was the best at the end. Ty for the great support.
