### ISSUE TITLE
Merge project with socket-controllers

### ISSUE THREAD

**Issue by pleerock** [pleerock/routing-controllers#106]
I have a plans to merge into this library socket-controllers library. Your thoughts about this decision? adding @19majkel94

**Comment by 19majkel94** [comment]
Actually, it's not a library but framework :wink: IoC and other blah blah definitions.

I'm into cooperation of routing- and socket-controllers but I'm not sure about merging this together. They are designed for different purposes and I can't imagine that you force koa users to get routing-controllers from npm together with sockets like you don't want to set express and koa as dependencies in package.json.

I see only one use-case scenario with integration - mixed controllers. Not mixed parameters in class methods (it makes no sense) but one controllers with REST API methods for HTTP and socket endopoint for push notification about changes from other users on this resource.

I'm not sure how much routing-controllers and socket-controllers codebases have in common and how to detect which method belong to which "library" - additional decorator is an inelegant solution, looks as bad as separate controllers.

**Comment by idchlife** [comment]
Guys I'm new here, fascinated by routing-controllers (my god @pleerock you are one magnificent sir for doing ORM like Doctrine and this controllers with decorators in TypeScript) and going to use it in the nearest projects, but what is socket-controllers? Where are they?

**Comment by pleerock** [comment]
@idchlife [there you are](https://github.com/pleerock/socket-controllers) this lib to use socket.io library with decorators

**Comment by idchlife** [comment]
Oh, thanks!

About topic, I guess one way is not to merge them making "routing+socket-controlles" but to create third library that will provide functionality for making a project with just choosing dependency like express or koa under the hood, allowing you to use it like a standalone framework for building projects. Maybe even with DI and TypeORM already attached/installed, for more convenient way to create projects using TypeScript + decorators at full power.

Because not everyone needs sockets with common routing or routing with sockets. That's why there are 2 separate libraries that for different functionality.

**Comment by pleerock** [comment]
> Maybe even with DI and TypeORM already attached/installed, for more convenient way to create projects using TypeScript + decorators at full power.

there is now discussion about complete framework (you can find [sample here](https://github.com/typestack/one/tree/master/sample) which contains everything-in-one.

> Because not everyone needs

thats something very hard to achieve. Because sometimes people need, sometimes they not... There is multer, session and some libraries used by this lib, but sometimes people don't need uploading. Even if I merge socket controllers into routing controllers in a separate framework - same question arrises there - maybe not all people need that.

**Comment by 19majkel94** [comment]
> There is multer, session and some libraries used by this lib, but sometimes people don't need uploading.

But they are hidden peer dependencies - you are not forced to install it if you don't use it. But there must be some code in `routing-controllers` codebase to provide support if it needs deep integration to work.

I don't mind about extension to integrate sockets into `routing-controllers` like [typeorm-routing-controllers-extensions](/typeorm/typeorm-routing-controllers-extensions)

>Even if I merge socket controllers into routing controllers in a separate framework - same question arrises there - maybe not all people need that.

There is a difference between framework like Angular or TypeStack, which are a collection of libs which cooperate together to help build big app, and IoC libraries aka framework like routing-controllers which focus only on one part of the app/technology. It's not a problem to deliver the gorilla and the entire jungle but it's bad when user only want banana.

**Comment by stonecold123** [comment]
I'm fine with either an extension or merge. I've been wanting for some sort of convenient tool for socket.io and routing controller. https://github.com/pleerock/routing-controllers/issues/100

**Comment by pleerock** [comment]
I decided not to merge them for now. Plan is to allow typestack cli to generate project with or without socket-controllers enabled.

**Comment by dulichan** [comment]
Is there an example that uses both these?

**Comment by pleerock** [comment]
specify controllers for socket controllers as well

**Comment by dulichan** [comment]
@pleerock I specified it (earlier I manually imported it before `useScoketServer`) but I am getting the same error. I am also attaching a screenshot of my backend error log. 

XMLHttpRequest cannot load http://localhost:9000/socket.io/?id=83&EIO=3&transport=polling&t=LoXMf_w. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:4300' is therefore not allowed access. The response had HTTP status code 404.

<img width="1440" alt="screen shot 2017-06-13 at 5 39 39 pm" src="https://user-images.githubusercontent.com/1016598/27081730-5975b704-505f-11e7-919b-c86a8af5eabc.png">

**Comment by dulichan** [comment]
I figured out the mistake I made. Posting the answer to anyone who encounters it. The mistake I made was assigning the express instance returned by `useExpressServer` to `this.app`.

```
    this.app = express();
    this.exp = this.app;
    this.app = require("http").Server(this.app);
    this.io = require("socket.io")(this.app);

    useSocketServer(this.io, {
      controllers: [__dirname + "/controllers/event/*.js"]
    });
    useExpressServer(this.exp, {
      routePrefix: "/v1",
      defaultErrorHandler: false,
      middlewares: [BoomMiddleware],
      authorizationChecker: authorization,
      controllers: [__dirname + "/connectors/**/mock/*.js"]
    });
   this.app.listen(PORT, () => {});
```
