### ISSUE TITLE
Ugly @MiddlewareGlobalAfter and @MiddlewareGlobalBefore

### ISSUE THREAD

**Issue by pleerock** [pleerock/routing-controllers#108]
I really don't like `@MiddlewareGlobalAfter` and `@MiddlewareGlobalBefore` names. I never did. What if we find a better name for those decorators or deprecate them and use simply:

```ts
@Middleware({ global: true, type: "after"|"before" })
```

instead? @19majkel94

**Comment by 19majkel94** [comment]
[+1 👍](https://www.youtube.com/watch?v=-uRi_xo92VEe)

Also we have to split middleware interface for koa and express.

**Comment by pleerock** [comment]
yes agree

**Comment by pleerock** [comment]
fixed in 0.7.0
