### ISSUE TITLE
The nodejs process will "Hang" if you open the flag of  logQueries.

### ISSUE THREAD

**Issue by qinyang1980** [pleerock/routing-controllers#111]
I use the PostMan to do the testing and found that if I open the logQueryies flag and then click the “send“ button very frequently. Finallly, the nodejs process will hang. No any errors pops up. No any logs are printed.

Another project in my company which only use typeorm and not use routing-controllers do not found this issue.

Please help me!
` 
  
      /**
       * Set to true if you want to log every executed query.
       */
      logQueries: true,

      /**
       * Set to true if you want to log error of the failed query.
       */
      logFailedQueryError: false,

      /**
       * If set to true then schema creation logs will be logged.
       */
      logSchemaCreation: false
`

**Comment by pleerock** [comment]
This sounds really weird. There is no relation between routing-controllers and typeorm's enabled logging. Can you setup a simple repo with reproduction of this problem? You can use `chakram` library instead of postman.

**Comment by pleerock** [comment]
Please reopen this issue if you are still have problems
