### ISSUE TITLE
Create a middleware that accepts arguments

### ISSUE THREAD

**Issue by stonecold123** [pleerock/routing-controllers#113]
I want to create a middleware that accepts parameters.  

Is using a function the only way of doing it? Are there any downsides compared to using a class with decorator `@Middleware()`?

Example:

````
function someMiddleWare(someVal:string) {
    return (req: any, res: any, next?: (err?: any) => any): any=>{
        res['someKey'] = someVal;
        next();
    }
}
````
````
@Get('/test')
@UseBefore(someMiddleWare('zzz'))
async getTest(){
    return 'something';
}
````

**Comment by idchlife** [comment]
Hey @stonecold123, doesn't your example already work? I think most of middlewares out there are plain functions for usage with @UseBefore

**Comment by stonecold123** [comment]
Yes, just t
