### ISSUE TITLE
Services are not injected to the controller

### ISSUE THREAD

**Issue by slavafomin** [pleerock/routing-controllers#116]
Hello!

I'm using `routing-controllers` with [Restify](http://restify.com/), however it's API is very similar to Express.js.

Here's how my server is configured:

```ts
import {
  useExpressServer as enableRoutingControllers,
  useContainer as useContainerForRoutingControllers
} from 'routing-controllers';

const server = restify.createServer();
server.use(restify.requestLogger());
useContainerForRoutingControllers(Container);
enableRoutingControllers(server, {
  controllers: [__dirname + '/../controllers/**/*.js']
});
server.listen(/**...*/);
```

Here's how my controller looks like:

```ts
import {JsonController, Get, Param} from 'routing-controllers';
import Logger = require('bunyan');

@JsonController()
export class UsersController {
  constructor (private logger: Logger) {
    this.logger.debug('UsersController.constructor()');
  }
  @Get('/users/:id')
  public getUser (@Param('id') id: number) {
    return 'GET USER: ' + id;
  }
}
```

However, `Logger` is not injected to the controller class. But, if I manually add `@Service()` decorator, it works fine.

Do you have any ideas why it's happening?

Have you tried to routing controllers with Restify? Is it supposed to work?

Thank you!

**Comment by pleerock** [comment]
you need to mark your controller with `@Service` decorator.

**Comment by slavafomin** [comment]
@pleerock Why do I need to mark it with `@Service` when it's already marked with `@JsonController`? Your example here doesn't use additional decorators: https://github.com/pleerock/routing-controllers#using-di-container.

**Comment by pleerock** [comment]
> Why do I need to mark it with @Service when it's already marked with @JsonController

because they are different libraries and purposes of both decorators are different. In `typedi` you can use services without having to mark classes with `@Service` decorator however if it will have other services injected you'll have problems, because without any decorator set on a class constructor parameters and their types wont be stored in reflect-metadata.

Same situation here. But I think we can resolve this issue and move reflect-metadata read from `@Service` decorator in some other place in the Container and check if it will work this way.

**Comment by slavafomin** [comment]
Yes, I understand that they are different and it makes sense with SRP and everything. However, I thought it could be convenient to use only the one decorator instead of two and your example in the documentation is using only one.

Considering moving reflection to the service layer — I think it's the best way to go. We will have centralized place where container is configured and decorators could be very thin, so their functionality could easily be replicated in other "aggregating" decorators of sort. And the DI could be configured without using any decorators at all, which is good for classes coming from third-party libraries where you can't add  decorators.

**Comment by slavafomin** [comment]
I've created an issue to track this work:
https://github.com/pleerock/typedi/issues/22#issue-223730630

**Comment by pleerock** [comment]
fixed in typedi.
