### ISSUE TITLE
Controllers middleware @UseBefore is executed before passport middleware that was attached to app before importing controllers.

### ISSUE THREAD

**Issue by idchlife** [pleerock/routing-controllers#120]
Is there any way to fix it? I'm using middleware to check for authentication status of user, but my check "if !request.user throw HttpUnautherizedError" is executed before user is event placed inside of request by passport-jwt.

**Comment by pleerock** [comment]
can you show a short peace of code?

**Comment by idchlife** [comment]
@pleerock 

this is my Authenticated middleware which I user with controllers (UseBefore for the whole class)

![image](https://cloud.githubusercontent.com/assets/4563032/25401870/a23b8562-29ff-11e7-8cc1-2b0f357abf40.png)

This is my main startup code in main server file:

![image](https://cloud.githubusercontent.com/assets/4563032/25401935/e019cb32-29ff-11e7-8074-b69773518715.png)

**Comment by pleerock** [comment]
> Controllers middleware @UseBefore is executed before passport middleware that was attached to app before importing controllers.

It is not possible, routing-controllers can't change somehow things you have already configure before using it. So debug and try to find real problem.
