### ISSUE TITLE
Custom decorators for sanitization/validation

### ISSUE THREAD

**Issue by slavafomin** [pleerock/routing-controllers#121]
Hello @pleerock @19majkel94!

I would like to implement custom decorators to be used with my own sanitization and validation components. However, I'm not sure if it's possible to completely achieve what I want and to integrate it properly with the `routing-controllers`.

I would specify my use case below and I would really appreciate if you will be able to give me some guidance toward it's implementation or clarifications on limitations:

```ts
@JsonController()
class UsersController {
  @Post('/users/')
  @Sanitize({
    query: {
      version: ['integer']
    },
    body: {
      email: ['string', 'email']
    }
  })
  @Validate({
    query: {
      version: ['version']
    },
    body: {
      email: ['email']
    }    
  })
  public createUser (
    result: object
  ) {
    // `result` is an automatically injected object:
    // { query: { version: 2 }, body: { email: 'john@example.com' } }
  }
}
```

Actually, my decorators looks more complex, but I've simplified this for the sake of clarity.

As you can see, I have two custom decorators that I want to use: `@Sanitize` and `@Validate`. I will try to formulate my questions:

1. How do I access `Request` from these decorators in order to access `query` and `body` properties?
1. How do I pass sanitized values from `@Sanitize` decorator to `@Validate` one?
1. And finally how do I inject the sanitization/validation result to the controller's action?

Is such implementation possible? I would greatly appreciate any hints. Thank you very much!

**Comment by pleerock** [comment]
what you want is probably wrapped middleware. For example you can do:

```ts
@Post()
@UseBefore((request, response, next) => {
     // ... validation logic
})
createUser
```

In your case you just need to create your own decorator and register middleware inside it (see how usebefore does it)

**Comment by slavafomin** [comment]
@pleerock thanks. And how do I pass data between those middleware? Do I attach it to the `request` object? Is there a way to directly inject it to the controller action?

**Comment by 19majkel94** [comment]
> And how do I pass data between those middleware?

Just attach the data to the `req` object as a property (`req.myData = { data }`) - JS is a dynamic language. 
If you think about the official way, use `res.locals` property to pass data between middlewares - [see docs](http://expressjs.com/en/api.html#res.locals).
