### ISSUE TITLE
Array parameters are not deserialized/validated properly

### ISSUE THREAD

**Issue by marshall007** [pleerock/routing-controllers#123]
Given the following decorated parameters on a controller method:

```ts
@QueryParam('fields') fields: string[],
@QueryParam('numbers') numbers: number[]
```

... the behavior of arrays in query parameters is inconsistent. Namely single values are not coerced to an array and the inner values are not coerced or validated against the appropriate type. Some examples:

```js
// GET ?fields=name
// -> ParameterParseJsonError: Value (\"name\") cannot be parsed to JSON

// GET ?fields=foo&fields=bar
console.log(fields) // -> [ "foo", "bar" ]

// GET ?numbers=1&numbers=2
console.log(numbers) // -> [ "1", "2" ] (works, but not deserialized)
```

**Comment by pleerock** [comment]
Right, its not possible to automatically find type of "string[]". You can do it with class-transformer, but your type should be object and inside it you should have your string[] with type set. 

Alternative could be to have `type` option in `QueryParam` options: `@QueryParam("fields", { type: String })`, but this is only needed for arrays, Im not sure if this functionality worth it.

**Comment by 19majkel94** [comment]
> You can do it with class-transformer, but your type should be object and inside it you should have your string[] with type set.

So it looks like all the problems with class-validator and class-transformer comes to one solution - #122 😉 I will try to look at the source code to see how much complicated is the implementation of this feature and whether I could help and contribute.

**Comment by pleerock** [comment]
I'll close it. If someone interested in fixing this issue feel free to create a PR. But I personally think it does not worth it. Better to create object and let class-transfromer to perform proper transformation directly into the object, instead of having each array in a separate query parameter.
