### ISSUE TITLE
Doesn't @Controller/@JsonController work with factory functions for classes?

### ISSUE THREAD

**Issue by idchlife** [pleerock/routing-controllers#125]
I want to use factoryFunction to create my controllers with some type and then extend them, i'm doing this:

```typescript
export function createLocationController<T extends ClassTypedInterface<LocationInterface>>(locationClass: T) {
  console.log("Creating class");

  @JsonController(`/locations/${locationService.get(locationClass).name}`)
  class LocationController {
    @Inject()
    protected locationService: LocationService;
    protected location;

    constructor() {
      this.location = this.locationService.get(locationClass);
    }
  }

  return LocationController;
}

```

and then I extend created class like this:

```typescript
export default class IntroLocationController extends createLocationController(IntroLocation) {
  @Inject()
  private playerService: PlayerService;

  @Get("/something")
  getSomething() {
    return true;
  }

// omitting...

```

In the end - there is not routes for this

**Comment by pleerock** [comment]
ahhh I really recommend you to keep it simple. You should mark your `IntroLocationController` as `@JsonController` to make it to work.

**Comment by idchlife** [comment]
Yeah, I'm kinda feeling that I'm abusing this comfortability of using decorators :D 

But it would've been nice possibility to do something like this. I'm having like 30> controllers in future that are based on same functionality and bootstrap code like service.getItemForThisExactController()

Anyway I'll keep it simple for now. Maybe in the future I'll find some nice solution like controllers as services (with abstract service controller as parent) or something like this. Hm.

Thanks!

**Comment by pleerock** [comment]
First try to keep your controllers as simple and small as possible. Second, prefer composition over such inheritance. Extract logic into repositories/managers/services/utils. I have hundreds controllers in my projects and always following these patterns.

**Comment by idchlife** [comment]
Yes, of course, I'm using composition and services much, because their behavior and functions should be separated. But sometimes you may use inheritance, it's not obsolete and can provide generating-code like behavior. In this example locations are classes for erm game like thing, with their behavior, and it would've been nice touch to generate some actions based on location methods but wrapped in action logic (http errors instead of location inner errors etc)

I mean generating code with factory functions and inheritance is nice.

Thanks for advices!
