### ISSUE TITLE
It seems that validation decorators are not working.

### ISSUE THREAD

**Issue by idchlife** [pleerock/routing-controllers#127]
Here I specify enableValidation: true

![image](https://cloud.githubusercontent.com/assets/4563032/25577809/c90259ac-2e71-11e7-8e7f-0dc20676b016.png)

Then I use it here:

```typescript

  @Post("/register")
  async register(
    @Req() request: Request,
    @Body() form: LoginForm,
    @Res() res: Response
  ): Promise<ObjectLiteral> {
    // Checking if user already exists by this username
    const user = await this.userManager.findUserBy({ email: form.email });

    if (user) {
      res.status(409);

      return {
        error: "User with this email already registered"
      };
    }
```

with class with constraints here:

```typescript
class LoginForm {
  @IsEmail()
  email: string;

  @MinLength(6)
  password: string;
}
```

Validation does not happen. It does not check for length or email.

**Comment by pleerock** [comment]
what routing-controllers version are you using? Adding @19majkel94

**Comment by idchlife** [comment]
@pleerock "routing-controllers": "^0.6.12",

**Comment by 19majkel94** [comment]
Can you show how you send the `LoginForm` from the client side? Do you send the credentials by AJAX (json string and `Content-Type: application/json`) or as `application/x-www-form-urlencoded` from the normal html form?

Does the `form` action param contains send data or it's just undefined or empty?

**Comment by idchlife** [comment]
@19majkel94 

sending it via json

![image](https://cloud.githubusercontent.com/assets/4563032/25670202/96cdaa58-3034-11e7-9c0d-92dc3bddc2bd.png)

Don't mind 409 conflict - it's about "email already registered" :D

**Comment by 19majkel94** [comment]
On `"0.7.0-alpha.9"` everything works ok, I have even created a special test case for the issue and it pass correctly:

```ts
describe.only("should throw validation error when body is incorrect", () => {

    let actioncalled = false;

    before(() => {
        getMetadataArgsStorage().reset();

        class LoginForm {
            @IsEmail()
            email: string;

            @MinLength(6)
            password: string;
        }

        @JsonController("/users")
        class ClassTransformUserController {

            @Post("/register")
            async register(
                @Body() form: LoginForm,
                @Res() res: any,
            ) {
                actioncalled = true;
                res.status(409);

                return {
                    error: "User with this email already registered"
                };
            }
        }

    });

    const options: RoutingControllersOptions = {
        validation: true
    };

    let expressApp: any, koaApp: any;
    before(done => expressApp = createExpressServer(options).listen(3001, done));
    after(done => expressApp.close(done));
    before(done => koaApp = createKoaServer(options).listen(3002, done));
    after(done => koaApp.close(done));

    assertRequest([3001, 3002], "post", "users/register", { email: "test", password: "test" }, response => {
        expect(response).to.have.status(400);
        expect(actioncalled).to.be.false;
    });
});
```
I can even see throwed ValidationErrors array on console. Other validation test cases passed correctly, even on `0.6.10` where the feature has been added.

So the problem is in your code, maybe you should try to create a minimum code sample for reproducing the issue?

**Comment by idchlife** [comment]
@19majkel94 I'll try to reproduce it again. Will write here with example code if problem stays.

**Comment by idchlife** [comment]
They seem to work now. Well, maybe I change something and that forced them to work, lol.
Closing this now.
