### ISSUE TITLE
inject-session-object

### ISSUE THREAD

**Issue by booradleys** [pleerock/routing-controllers#128]
Hi,
I don't understand how to inject sessions
https://github.com/pleerock/routing-controllers#inject-session-object

I've installed express-session.

import { Session } from "routing-controllers";
//import * from "express-session";
var session = require('express-session');

@Post("/login/")
loginUser(@Session() session: Express.Session, @Body() user: User) {
}

How to find such a "Express.Session" type ? How and what to import ?

**Comment by pleerock** [comment]
adding @19majkel94

**Comment by 19majkel94** [comment]
> How to find such a "Express.Session" type ? How and what to import ?

`npm i -s express @types/express`

`Express` is a global namespace so no imports are needed.

**Comment by booradleys** [comment]
Thank you very much @19majkel94, it works fine!
I also need to use/inject in my controllers:
- express-translate (https://github.com/uber/express-translate)
- passport auth (http://passportjs.org/docs)
It would be great to have a short explanation, to do that ;-)
Whatever, thank you very much for your job !

**Comment by 19majkel94** [comment]
Just use the [`@Req()` decorator](https://github.com/pleerock/routing-controllers#method-parameter-decorators) to inject the whole Request object like in normal express handler. Or write [custom decorator](https://github.com/pleerock/routing-controllers#custom-parameter-decorators) that will extract and inject that for you 😉

**Comment by pleerock** [comment]
I think this can be closed
