### ISSUE TITLE
feature: allow to register custom middleware for sending response

### ISSUE THREAD

**Issue by NoNameProvided** [pleerock/routing-controllers#129]
Currently sending the response to the client is handled by routing-contollers in `routing-controllers/src/driver/express/ExpressDriver.ts`  via:

```ts
if (action.isJsonTyped) {
  options.response.json(result);
} else {
  options.response.send(result);
}
```

This prevents to have a global handler for responses like we have for errors with `ExpressErrorMiddlewareInterface`. It would make sense to have an `ExpressResponseMiddlewareInterface`

The use case I need this is to auto format response based on its type, I simply return object (`findOneById`) or array (`findAndCount`) from typeORM and I would like to wrap it in a general response. 

For objects: 

```js
{
  payload: object
}
```

For lists

```js
{
  meta: {
    count: count,
    limit: @param('limit'),
    offset: @param('offset'),
  }
  payload: Type[]
}
```

Now I cant do this, because when my middlewares are loaded the response is already sent.

Implementation can be:

1. Organize default response sending logic as a middleWare
2. Add option to provide a  custom`ExpressResponseMiddlewareInterface`  middleware

**Comment by 19majkel94** [comment]
There was already the feature like this, it was called `interceptors` but  it has been removed it from the code as it looked like nobody was using it 😆 
https://github.com/pleerock/routing-controllers/tree/16e80b16d0e2d1ee1429af87087544eb25c75e5d#using-interceptors

Now I see a good use case of this functionality and I think we could bring it back 😉 
But first we have to think about the API - I would also love to see an [exception filters](https://kamilmysliwiec.gitbooks.io/nest/content/advanced/exception-filters.html) which would help in catching errors and mapping it to the nice response object. What do you think @pleerock?

**Comment by NoNameProvided** [comment]
> There was already the feature like this, it was called interceptors but it has been removed it from the code as it looked like nobody was using it.

Yeah I saw something about it in one of the issues that @pleerock was concerned about removing that feature. 😄 

> Now I see a good use case of this functionality and I think we could bring it back 😉

Yeah lets do that, it is very common to manipulate responses before actually sending them down the wire

> I would also love to see an exception filters which would help in catching errors and mapping it to the nice response object. 

How is it different from just letting the error propagate to your custom error handler where you handle it in an unified way? The only use-case I see if someone would need to tear-down resources when an error happen, but since JS is garbage collected I dont see such case. (Except if the express app call some C++, Rust, etc.. native code.)

> But first we have to think about the API

Yes we should, in the last few weeks I just fell in love with all the stuff that @pleerock has built, but because they are immature, there are some rough edges left. It would be really awesome if we can sort those out and I am happy to help! But we should open a different ticket for that conversation.

**Comment by pleerock** [comment]
interceptors are 🔙  in the latest version
