### ISSUE TITLE
bug: 0.7 version is not released

### ISSUE THREAD

**Issue by NoNameProvided** [pleerock/routing-controllers#130]
Changelog says there is a `0.7` release but running `npm info routing-controllers` will show the latest published version is `0.7.0-alpha.8`. Which for example doesn't have the `ActionProperties` interface mentioned in docs.

**Comment by pleerock** [comment]
I exported ActionProperties in `0.7.0-alpha.9`> I'll publish 0.7.0 once alphas gonna be well tested by users.
