### ISSUE TITLE
Unifying creating app interface

### ISSUE THREAD

**Issue by 19majkel94** [pleerock/routing-controllers#135]
I wonder @pleerock, whether we really need two separate functions: `createExpressServer` and `useExpressServer`. Maybe we could unify it and provide an single function with signature:
```ts
export function createExpressServer(options?: RoutingControllersOptions, expressApp?: express.Application): express.Application;
```
So the usage would be very simple:
```ts
// like now
createExpressServer({
    routePrefix: "/api",
    controllers: [__dirname + "/../controllers/*.js"],
});

// new API
const app = express();
app.use(bodyParser.json());

createExpressServer({
    routePrefix: "/api",
    controllers: [__dirname + "/../controllers/*.js"],
}, app);
```

I know that in some cases you doesn't specify options but need to use express app, so it's not the best solution with this signature (`createExpressServer({}, app);`). Maybe overloading is a better solution that separate functions?

```ts
export function createExpressServer(): express.Application;
export function createExpressServer(options: RoutingControllersOptions): express.Application;
export function createExpressServer(expressApp: express.Application): express.Application;
export function createExpressServer(options: RoutingControllersOptions, expressApp: express.Application): express.Application;
```

And we don't have to make `express` a dependency of `routing-controllers` - for type safe only lightweight `@types/express` has to be a dep and we can then do `import * as express from "@types/express";` 😉

**Comment by pleerock** [comment]
We can't have `@types/express` dependency. Because if we add `@types/express` then we have to add `@types/koa` too (and express body-parser, koa body-parser and others). You are as express users wont have koa typings, right? Same for koa users - they wont have express typings in their apps. I don't think its a problem that `createExpressServer` returns any - users simply need to cast variable, and they do it only once, because `createExpressServer` is used only once in whole application.

```ts
createExpressServer({
    routePrefix: "/api",
    controllers: [__dirname + "/../controllers/*.js"],
}, app);
```

I don't like this syntax. `app` in the end looks really bad and not visible from the first sight. Its better to have `useExpressServer` instead of having such syntax.

**Comment by 19majkel94** [comment]
> You are as express users wont have koa typings, right? 

This is a node.js lib, right? Or should we care about bundle size and other stuff's? 😜 

For me it's better to have koa typings in express project than having `any` everywhere. Typings have only a few KB to download from npm, it's not a whole libraries with unnecessary few MB. We already have a lot of trash in node_modules:
https://medium.com/friendship-dot-js/i-peeked-into-my-node-modules-directory-and-you-wont-believe-what-happened-next-b89f63d21558

> app in the end looks really bad and not visible from the first sight

Right, it should have look like this:
```ts
export function createExpressServer(): express.Application;
export function createExpressServer(options: RoutingControllersOptions): express.Application;
export function createExpressServer(expressApp: express.Application): express.Application;
export function createExpressServer(expressApp: express.Application, options: RoutingControllersOptions): express.Application;
export function createExpressServer(appOrOptionsParam?: express.Application|RoutingControllersOptions, optionsParam?: RoutingControllersOptions): express.Application {
    // overload implementation
}
```
But there might be some problem with interface narrowing in typescript, it would be hard to check if appOrOptionsParam is an express app or options object.

**Comment by NoNameProvided** [comment]
> This is a node.js lib, right? Or should we care about bundle size and other stuff?

Actually we should. Eg: heroku limits the size an app can use, so it's still matter for node apps as well. Also having tons of stuff in the node_modules because we can is not the best approach.
