### ISSUE TITLE
classTransformer instead of useClassTransformer

### ISSUE THREAD

**Issue by vlio20** [pleerock/routing-controllers#139]
Seems like the option is `classTransformer` instead of `useClassTransformer` (this one is in the docs which is a bit misleading).
`useClassTransformer ` is missing form `RoutingControllersOptions`.

I don't mind to PR in order to change the docs.

**Comment by pleerock** [comment]
you are correct. In past it was called `useClassTransformer`, now its called simply `classTransformer`. Next time feel free to create PR directly for such issues. Thank you
