### ISSUE TITLE
Rationale for not supporting "required" session params?

### ISSUE THREAD

**Issue by marshall007** [pleerock/routing-controllers#140]
It seems like `@Session(<param>, { required: <true|false> })` should work to be consistent with `@Param`, `@QueryParam`, `@Body`, etc.

I can maybe understand why `@Session({ required: false })` isn't supported, but even so I think it's unnecessarily opinionated to not support the `required` option on session params.

**Comment by NoNameProvided** [comment]
`@Param` defaults to required and there is no option to control it.

**Comment by 19majkel94** [comment]
`@Session` is required because when we demand session object, it must exist (working session middleware). Also `@Session(propertyName)` is required because you inject it to read a property like user, to perform login just use `@Session` and assign `session.prop = value`.

Can you show me the use case when you want something from session but you maybe don't want it so it can be undefined?

**Comment by marshall007** [comment]
@19majkel94 yea sure. We have several endpoints that can be hit whether or not you have a session. If you have a session, it uses the customer ID from your session to fetch and layer in additional customer-specific data into the response.

**Comment by 19majkel94** [comment]
You're right, I forgot that routing-controllers can be also used for MVC apps, not only REST API where you return 404 if user has no access to the resource (is not logged in). In case of rendering view, you can e.g. render home page for guest and personalized for user in the same action handler, so optional parameter makes sense there. But `@Session` should stay required as it will be empty object even for guests, undefined only if there's no `express-session` middleware installed.

Will do the fix today 😉

**Comment by marshall007** [comment]
@19majkel94 awesome, thanks! My use case is actually just a REST API. It is essentially a proxy that sits in front of our product search service and layers in customer-specific product data from a redis cache into the response if you have a valid session.
