### ISSUE TITLE
@CurrentUser http status code

### ISSUE THREAD

**Issue by Diluka** [pleerock/routing-controllers#141]
If `@CurrentUser({required: true}) user: any` don't load any user, routing-controllers will response http status `403 Forbidden`. I think returning `401 Unauthorized` is better.
see http://stackoverflow.com/questions/3297048/403-forbidden-vs-401-unauthorized-http-responses

**Comment by pleerock** [comment]
yeah 401 looks like more proper code. Adding @19majkel94

**Comment by 19majkel94** [comment]
Yeah, 401 is correct. I always use this middleware with `UnauthorizedError`:
```ts
    use(req: express.Request, _res: express.Response, next?: express.NextFunction) {
        if (!req.session || !req.session.user || !req.session.user.id) {
            throw new UnauthorizedError("Access denied, you have to login first!");
        }

        if (next) {
            next();
        }
    }
```

**Comment by Diluka** [comment]
Now `@CurrentUser` returning 401 is right, but `@Authorized` returning 401 too. `@Authorized` should be 403 and it is right before.

**Comment by pleerock** [comment]
ahh whyy arent they same

**Comment by Diluka** [comment]
@pleerock 
`401` means not login
`403` means no permission to access, maybe logged in, e.g. role mismatch

**Comment by pleerock** [comment]
but having `@CurrentUser({ required: true })` and `@Authorized()` is actually same - both checks if user login or not, which means 401. Only authorized with role specified is what you are talking about

**Comment by Diluka** [comment]
The truth is `@Authorized("some_role")` throws `401` too. The checker only returns `true` or `false`. How can it know which code will be returned? Just make it simple, `@Authorized()` always returns `403`.

**Comment by pleerock** [comment]
> Just make it simple, @Authorized() always returns 403.

it will be confusing because `@CurrentUser({ required: false })` and `@Authorized()` without role are equal things. It will be confusing if we set 401 in one case and 403 in another. Maybe to make it simple they both shall always return 403?

**Comment by Diluka** [comment]
The real confusing is `@CurrentUser` and `@Authorized` using the same status code, no matter is `401` or `403`.

`@CurrentUser({ required: true })` should be `401`
`@Authorized("some_role")` should be `403`
`@Authorized()` should better be `401`, but `403` also acceptable

So I said...

> Just make it simple, `@Authorized()` always returns `403`

**Comment by Diluka** [comment]
created a PR #178 to fix the status code
