### ISSUE TITLE
How to get `multipart/form-data` text field?

### ISSUE THREAD

**Issue by fengcen** [pleerock/routing-controllers#156]
I use `@BodyParam` but the value is `undefined`.

**Comment by 19majkel94** [comment]
Have you tried to apply a middleware for extrating params from POST request?

```ts
var express = require('express')
var bodyParser = require('body-parser')

var app = express()

// parse application/x-www-form-urlencoded
app.use(bodyParser.urlencoded({ extended: false }))

// and then
useExpressServer(app, options)
```

**Comment by fengcen** [comment]
I use koa, and my question is get text field from `multipart/form-data`.

In `KoaDriver.ts`:
```
    if (actionMetadata.isFileUsed || actionMetadata.isFilesUsed) {
            const multer = this.loadMulter();
            actionMetadata.params
                .filter(param => param.type === "file")
                .forEach(param => {
                    defaultMiddlewares.push(multer(param.extraOptions).single(param.name));
                });
            actionMetadata.params
                .filter(param => param.type === "files")
                .forEach(param => {
                    defaultMiddlewares.push(multer(param.extraOptions).array(param.name));
                });
        }
```
Does routing-controllers only parse file? How to get the text fields?

**Comment by 19majkel94** [comment]
`routing-controllers` loads `koa-multer` only if you decorate your action param with `@File()` decorator. If you don't use files in your action, you should use `application/x-www-form-urlencoded` instead of `multipart/form-data` to send data from the form. If you can't - you have to configure the koa-multer middleware by yourself, maybe in `@UseBefore`.

**Comment by fengcen** [comment]
I upload with `FormData` which contains both file and text fields. The file works as expected.
But the text fields is `undefined`.

My controller:
```
    @Post('/test')
    public async signUp( @Ctx() ctx: any, @UploadedFile('test') test: any, @BodyParam('name') username: string) {
        console.log(test);
        console.log(username);
        ctx.redirect('/');
    }
```

**Comment by 19majkel94** [comment]
This is really weird. Parsing text fields is a side effect of parsing file input, at least it's how it works in express. Can you check if the param is in the body, or the ctx body is empty or undefined?

**Comment by fengcen** [comment]
Thanks for your help. I had tried. I test it in windows and it works find. But the text value is `undefined` when I test in mac. I confirm that the request body is not empty with `on('data')`. I will update this issue once I get an answer.

**Comment by tangdw** [comment]
？
