### ISSUE TITLE
0.7.0 release

### ISSUE THREAD

**Issue by pleerock** [pleerock/routing-controllers#161]
I'm planning to release 0.7.0. Any concerns about it? Is it good to go? Didn't we left anything undocumented in changelog, or do we have some another breaking change we should introduce before releasing? What you your thoughts?

**Comment by pleerock** [comment]
Would be very great if someone can make [sample repositories](https://github.com/pleerock/routing-controllers#samples) up-to-date once I release it.

**Comment by NoNameProvided** [comment]
I can take care of the express one before the weekend.

**Comment by NoNameProvided** [comment]
Hey @pleerock

Just created a pull request: 👉 pleerock/routing-controllers-express-demo/pull/1. It's very basic, just updates the deps and adds some more comments. 

Can we pimp the demo a little bit? My ideas are:

 - adding TypeORM with sqlite
 - example middlewares 
 - example special middlewares (`AuthorizationChecker` & `CurrentUserChecker`)
 - example error handler
 - others?

**Comment by NoNameProvided** [comment]
And an another one: 👉 pleerock/routing-controllers-koa-demo/pull/3.

**Comment by pleerock** [comment]
Thank you.

> Can we pimp the demo a little bit?  

basic example should be simple as possible. What you are suggesting should be done in a separate 
"routing-controllers advanced demo" repository

**Comment by marshall007** [comment]
@pleerock I don't think it would be bad to have an `AdvancedController` highlighting advanced use cases. I think it's feasible to do that in a way that doesn't detract from the minimalist example in the same repo.

**Comment by pleerock** [comment]
its not about `AdvancedController` but also about having lot of other dependencies like typeorm, sqlite typeorm-routing-controllers-extension etc. It brings complexity for newcomer users who dont need/know all these tools, I won't that.

**Comment by pleerock** [comment]
okay I made a `0.7.0` release. Demos are updated thanks to @NoNameProvided . Only https://github.com/pleerock/routing-controllers-angular2-demo left non updated :(
