### ISSUE TITLE
Transform array in Body decorator.

### ISSUE THREAD

**Issue by yantrab** [pleerock/routing-controllers#168]
Hi, if id do  :
```
  @Post('/save')
    save( @Body() halls: Hall) { }
```

the "halls" hold array of hall.
But is i do :
```
  @Post('/save')
    save( @Body() halls: Hall[]) { }
```

the "halls" hold array of object.

How can i fix it?

tanks a lot.

**Comment by pleerock** [comment]
You have array of objects because we cant automatically determine type of array parameters (because typescript do not allow to do that). You can fix it however by explicitly provide a type to a decorator:

```@Body({ type: Hall }) halls: Hall[]`
