### ISSUE TITLE
ErrorHandler decorator

### ISSUE THREAD

**Issue by peterjp80** [pleerock/routing-controllers#17]
The documentation mentions using the `@ErrorHandler()` decorator, but that decorator doesn't exist.

**Comment by peterjp80** [comment]
What I'm trying to do is send back a user-friendly error message to the client.  I'd like to accomplish that with an error handler, but I can't because the `handleError()` method in ExpressDriver calls either `response.json()` or `response.send()`.  That's called before the error handlers are called, so when I try to do a `response.json()`, I get the error _"Can't set headers after they are sent."_

I tried to use an interceptor to accomplish this instead, but I return a promise, and in the `handleResult()` method of RoutingControllerExecutor, the interceptors aren't used if the promise gets rejected.

I'd be interested in building out functionality to use an `@ErrorHandler()` decorator to create an "error interceptor".  These error interceptors would be called before the `handleError()` method in the Drivers call the `json()` or `send()` method on the response.  I'd be happy to fork and submit a pull request if that's okay with you.

**Comment by pleerock** [comment]
Looks like its an error in documentation. It should be marked as `@Middleware` instead. See sample [here](https://github.com/pleerock/routing-controllers/blob/master/sample/sample6-global-middlewares/AllErrorsHandler.ts) 


```typescript
import {MiddlewareGlobalBefore, ErrorMiddlewareInterface} from "routing-controllers";

@MiddlewareGlobalBefore()
export class AllErrorsHandler implements ErrorMiddlewareInterface {

    error(error: any, request: any, response: any, next?: Function): void {
        console.log("Error handled: ", error);
        next(error);
    }
    
}
```

**Comment by peterjp80** [comment]
Using `@MiddlewareGlobalAfter()` worked as far as wiring up the error handler goes, but I still receive the error _"Can't set headers after they are sent"_ when my error handler calls `response.json()` (see my 2nd post in this thread for explanation of why).  Should I open a separate issue for this?

**Comment by Diluka** [comment]
I have the same problem. The default error middleware inside `ExpressDriver` send respone before my custom error middlewares. So my error middlewares can do nothing about the sent result.
