### ISSUE TITLE
@Authorized() flexibility

### ISSUE THREAD

**Issue by jselesan** [pleerock/routing-controllers#170]
Hi all! I was thinking that the authorization mecanism has a lack of flexibility, since it only allows a role-based authorization. It would be nice to allow things like user-based authorization (like in ASP.Net MVC) and even user "level" authorization. Something like this:
```
@Authorized( { users: ["Jhon", "Joe" ] } )
```
or
```
@Authorized( { userLevel: 3 } )
```

Perhaps we could raname the "roles" parameter of @Authorized to "authorizationData" as object

**Comment by pleerock** [comment]
I think we can do that. Will be released in `0.7.0-alpha.15`
