### ISSUE TITLE
Routing .ts files in directories

### ISSUE THREAD

**Issue by gonzalo-trenco** [pleerock/routing-controllers#171]
Hi!

I've been trying a while to setup routing via directories as sampled [here]( https://github.com/pleerock/routing-controllers/blob/master/sample/sample11-complete-sample-express/app.ts)

I saw that .ts files can be loaded into a controllers array, but i can't get it to work correctly.
If I import one by one the controllers and push them into the array it works fine, but using directory formula it just does not load anything into the bundle generated by webpack.

```typescript
const app = createExpressServer({
    controllers: [baseDir + "/controllers/**/*.controller.ts"]
});
```

are those .ts files passed to the transpiler to link them?
I'm using webpack with this ` .tsconfig.json`

```json
{
    ...
    "compilerOptions": {
    "module": "commonjs",
    "moduleResolution": "node",
    "target": "es6",
    "sourceMap": true,
    "watch": true,
    "outDir": "build",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true
  },
  "exclude": [
    "node_modules"
  ]
}
```

Any clue?
Thanks!!

**Comment by NoNameProvided** [comment]
When you writing a Typescript app, it will compile down to JS so in your build directory the files will have `.js` extension.

So if you computed baseDir is correct (so it's point to your build folder if it's an absolute path), then the only thing you have to do is to rename `.ts` to `.js`:

```ts
const app = createExpressServer({
    controllers: [baseDir + "/controllers/**/*.controller.js"]
});
```

**Comment by gonzalo-trenco** [comment]
Thanks, i finally figured it out.
The case is that I'm trying to achieve dynamic import of my .ts controllers into the webpack bundle with the least possible effort.
Right now, only controller index will grow as the app goes large and also can work as an ACL as well with a little tweaking.

So far, i created an index.ts over `/src/controllers` with this pattern:
```
export * as test from "./test/test.controller.ts"
export * as echo from "./echo/echo.controller.ts"
```

and in my Express setup

  ```
export class Express {
        public app: express.Application;
        controllers: Array<any> = [];
        private config() {
            useExpressServer(this.app, {
                controllers: this.controllers
            });
        }
        private routes() {
            let loadedControllers = this.controllers;
            for (let controller in controllers) {
                loadedControllers.push(controllers[controller]);
            }
        }
        public start(port: number) {
            this.app.listen(port);
            console.log('Server Listening on Port', port);
        }
        constructor() {
            this.app = express();
            this.routes();
            this.config();
        }
    }
```

Any thoughts?
