### ISSUE TITLE
Has anyone got inversify to work with this package?

### ISSUE THREAD

**Issue by rucas** [pleerock/routing-controllers#175]
Just trying to get `useContainer` to work with [inversify](https://github.com/inversify/InversifyJS) not injecting anything at the moment.

code looks like this:

index.ts
```typescript
const app: express.Express = express();
useContainer(container);
useExpressServer(app, {
   controllers: [__dirname + "/controllers/*.ts"],
});
```

container.ts
```typescript
let container = new Container();

container
  .bind<IController>(TYPES.ChangelogController)
  .to(ChangelogController)
  .whenTargetNamed("ChangelogController");

export { container }
```

Getting errors: 
```
Error: No matching bindings found for serviceIdentifier: ChangelogController
Registered bindings:
 ChangelogController - named: ChangelogController
```
```
at ActionMetadata.callMethod .../packages/..../src/metadata/ActionMetadata.ts:254:39)  
at ..../packages/..../src/RoutingControllers.ts:123:142
```

**Comment by pleerock** [comment]
I think you need to register your controllers in inversify framework since inversify requires all services to be registered in it. There were previous discussions on how to make it work and seems people do it.

**Comment by rucas** [comment]
@pleerock I registered the controller in inversify, but that seems to not help still getting the same error with `ActionMetadata.callMethod` I even logged out the container before and after `useContainer` and see the controller in there. Any Ideas?

**Comment by rucas** [comment]
Never-mind I got it to work by doing this:
```typescript
container
  .bind<IController>(ChangelogController)
  .toSelf();
```

**Comment by pleerock** [comment]
Looks like its solved

**Comment by appsolutegeek** [comment]
Yes I also got it to work using toSelf but everytime a call comes into my controller it creates an instance of it 2 times. I have placed a console.log inside the constructor and it is being called twice.

**Comment by JeanGatto** [comment]
> Yes I also got it to work using toSelf but everytime a call comes into my controller it creates an instance of it 2 times. I have placed a console.log inside the constructor and it is being called twice.

Hey, try to define the scope type:
`const container = new Container();`
`container.bind<ControllerBase>(UserController).toSelf().inSingletonScope()`
