### ISSUE TITLE
JsonResponse and TextResponse is removed in 0.7.0?

### ISSUE THREAD

**Issue by OysteinAmundsen** [pleerock/routing-controllers#176]
```
error TS2305: Module '"./node_modules/routing-controllers/index"' has no exported member 'JsonResponse'.
error TS2305: Module '"./node_modules/routing-controllers/index"' has no exported member 'TextResponse'.
```

This is not documented in your changelog. What is it's replacement?

I'm using this feature for a controller which should return JSON in some endpoints, but plain text or Handlebars rendered HTML in others. I do not want to split up the controller into a JsonController and a regular Controller, as all endpoints fit logically under the same url path for my use.

**Comment by pleerock** [comment]
Yeah they are removed, sorry forgot to mention that in changelog. JsonResponse and TextResponse bring lot of issues and confusion into the framework thats why it was decided to remove them. Unfortunately you have to split your controllers. But its not _that_ bad...

**Comment by OysteinAmundsen** [comment]
Hmm... Wonder if it's perhaps easier to specify content-type manually and return a JSON.stringify on each endpoint required to return JSON. Trying that first.
