### ISSUE TITLE
use classTransformer only for input

### ISSUE THREAD

**Issue by jselesan** [pleerock/routing-controllers#179]
Hi there. A time ago, I had to disable classTransformer (in useExpressServer) because it didn't work fine with mongoose models, but now, I would like to take advantage of classTransformer to transform the query params to an object, so it would be nice to have the ability to enable classTransformer only for the input and keep it disabled for output. Is it posible?

**Comment by pleerock** [comment]
no I don't think its possible right now. What problem do you have with mongooose models? Maybe `@Exclude` can help you in your mongoose models?

**Comment by ruiming** [comment]
It would be nice to have a option to disable transform on response.
Return a sequelize instance or mongoose instance both throw error.

I now doing this to disable transform on response:

```typescript
import { KoaDriver } from 'routing-controllers/driver/koa/KoaDriver'

const originHandleSuccess = KoaDriver.prototype.handleSuccess
KoaDriver.prototype.handleSuccess = function () {
  this.useClassTransformer = false
  return originHandleSuccess.apply(this, arguments)
}
```

**Comment by pleerock** [comment]
thats why you should use typeorm instead of sequelize or mongoose 😝 . But seriously it should be easily fixed if you do something like this in your models:

```ts
@Exclude()
_id: string;

@Expose()
get id() {
    return this._id.toString(); // or some other method that normalizes that id
}
```

**Comment by 19majkel94** [comment]
Closing as a duplicate in favor of #266.
Please subscribe there to be notified when the required changes land.

**Comment by AnimaMundi** [comment]
@ruiming Nice workaround, thanks!

@pleerock I really appreciate the work you've done with routing controllers so far, it's great! But I believe a library like this should be agnostic of any data mappers being used rather than being developed to suit only TypeORM.

**Comment by pleerock** [comment]
It does not "suit typeorm". class-transformer is generic serializer and does work with object. In mongodb you have complex MongoID object and it simply tries to serialize it as well. The issue with complexity of mongoid object, not with class-transformer.

**Comment by AnimaMundi** [comment]
> thats why you should use typeorm instead of sequelize or mongoose

I was referring to your comment, which implies you shouldn't be using anything other TypeOrm with routing-controllers.

**Comment by pleerock** [comment]
I didnt say that routing-controllers cannot be used with anything else except typeorm. It was simple advice and a bit of joke as you can see from "😝" smile I used.

**Comment by AnimaMundi** [comment]
Okay that's my bad 😆 sorry for misunderstanding!

**Comment by pleerock** [comment]
BTW you should really try TypeORM 😝

**Comment by AnimaMundi** [comment]
If TypeORM had full support for Mongoose then I would gladly, but unfortunately it doesn't 😢 but I'm working on a similar project to TypeORM specifically for Mongoose myself at the moment to compensate 😉

**Comment by jselesan** [comment]
> I'm working on a similar project to TypeORM specifically for Mongoose myself at the moment to compensate

 +1 to that!

**Comment by pleerock** [comment]
It does not have all features mongoose has, but it does have all required features to make really good applications using mongodb.

**Comment by AnimaMundi** [comment]
The last I checked, it had only "basic" MongoDB support. Which is great, I'm glad to see it going in that direction and I mean no offense or to put down TypeORM in any way because I think it's an absolutely fantastic project. But Mongoose is extremely advanced and has a lot of features which personally I could not feel like I could do without, I am very heavily invested in that particular technology in a lot of projects. My TypeORM-like project will just be a simple enough tool that converts classes into Mongoose compatible schemas and leave mostly everything else up to Mongoose. All hail Mongoose 🙏 📿

**Comment by smithdalec** [comment]
Those using Sequelize: you can return the result of your model instance's `toJSON` method to the action method in order for `class-transformer`'s serialization to work properly

**Comment by rochapablo** [comment]
Any update about this?

**Comment by sabereen** [comment]
This is my workaround:

```
// Disable classToPlain class-transformer
require('class-transformer')['classToPlain'] = function (obj: object)  {
    return JSON.parse(JSON.stringify(obj))
}
```
