### ISSUE TITLE
undefined in a HTTP POST body

### ISSUE THREAD

**Issue by Diluka** [pleerock/routing-controllers#18]
I wrote a handler like this. When I use form post or Postman's post, it gets an empty object. 
But I use supertest to test it, it seems OK, and get the right body object.

request.body is always undefined.

```
    @Post("/")
    async saveOne(@Body() data) { //data is {} if not in test
        return await this.todoService.save(data);
    }
```

test code: **PASS**
```
"use strict";
describe("Todo测试", ()=> {
    const expect = require("chai").expect;
    const supertest = require("supertest");
    const request = supertest.agent(`http://localhost:${process.env.LEANCLOUD_APP_PORT}`);

    it("写入对象", (done)=> {
        request.post("/todos").send({"content": `测试数据 - ${new Date()}`}).expect(200).end((e, res)=> {
            expect(res.body).to.be.an("object", "返回对象");
            done();
        });
    });
});
```

Chrome's POST form submit: **FAILED**
```
curl 'http://localhost:3000/todos' -H 'Origin: http://localhost:3000' -H 'Accept-Encoding: gzip, deflate' -H 'Accept-Language: zh-CN,zh;q=0.8' -H 'Upgrade-Insecure-Requests: 1' -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36' -H 'Content-Type: application/x-www-form-urlencoded' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8' -H 'Cache-Control: max-age=0' -H 'Referer: http://localhost:3000/' -H 'Connection: keep-alive' -H 'DNT: 1' --data 'content=test' --compressed
```

Postman's curl: **FAILED**
```
curl -X POST -H "Cache-Control: no-cache" -H "Postman-Token: e06e03e8-6009-28f6-59cc-0cc72ac6dfbc" -H "Content-Type: application/x-www-form-urlencoded" -d 'content=value to be save&ignore=value to be ignore' "http://localhost:3000/todos"
```
p.s. just ignore those Chinese characters,there're nothing to do with this issue, consider them just strings

**Comment by Diluka** [comment]
full sample is here https://github.com/Diluka/leancloud-demo/tree/demo-post-body-is-empty

**Comment by pleerock** [comment]
did you set a Content-type: application/json in your request?

**Comment by Diluka** [comment]
I tried, it's the same. And the normal html form doesn't json, it's not work too

**Comment by Diluka** [comment]
I solve this problem, but I consider it's maybe a bug.

this is not work:
```
export const app: Express.Application = createExpressServer({
    controllerDirs: [__dirname + "/controller/**/*.controller.js"],
    middlewareDirs: [__dirname + "/middleware/**/*.middleware.js"],
    interceptorDirs: [__dirname + "/interceptor/**/*.interceptor.js"]
});

app.use(json());
app.use(urlencoded({extended: true}));
```

this is work:
```
import {json, urlencoded} from "body-parser";
import {MiddlewareInterface, MiddlewareGlobalBefore} from "routing-controllers";

@MiddlewareGlobalBefore({priority: 2})
export class JsonBodyParserMiddleware implements MiddlewareInterface {
    use(request: any, response: any, next?: (err?: any) => any): any {
        return json()(request, response, next);
    }
}

@MiddlewareGlobalBefore({priority: 3})
export class UrlencodedBodyParserMiddleware implements MiddlewareInterface {
    use(request: any, response: any, next?: (err?: any) => any): any {
        return urlencoded({extended: true})(request, response, next);
    }
}
```

And the readme tells me to install body-parser, but it seems I shall use it by hard code

**Comment by pleerock** [comment]
> I tried, it's the same. And the normal html form doesn't json, it's not work too.
Besides, the request body is always undefined, how can I use middleware to deal with?

if you are working with json, you should always specify json content headers

> export const app: Express.Application = createExpressServer({
    controllerDirs: [__dirname + "/controller/**/*.controller.js"],
    middlewareDirs: [__dirname + "/middleware/**/*.middleware.js"],
    interceptorDirs: [__dirname + "/interceptor/**/*.interceptor.js"]
});
app.use(json());
app.use(urlencoded({extended: true}));

You are doing it wrong. `createExpressServer` creates and bootstraps express server. You probably should do you logic before it bootstrap the app. To do that you need to create your own express server and use `useExpressServer` instead. Something like this:

```typescript
const app = express();
app.use(json());
app.use(urlencoded({extended: true}));
useExpressServer({
    controllerDirs: [__dirname + "/controller/**/*.controller.js"],
    middlewareDirs: [__dirname + "/middleware/**/*.middleware.js"],
    interceptorDirs: [__dirname + "/interceptor/**/*.interceptor.js"]
});
```

**Comment by Diluka** [comment]
thx,  I get it. 
I will use `useExpressServer` instead

**Comment by Diluka** [comment]
but I still have a question

when I use json params to post, how can I do pre-process in a middleware.
at the beginning, the json params successfully inject into the method params, but I can't get it from req.body
