### ISSUE TITLE
Pipe stream to response returns 404

### ISSUE THREAD

**Issue by Luke265** [pleerock/routing-controllers#180]
How to send a stream?

````
import {Get, JsonController, Res} from "routing-controllers";

@JsonController('/test')
export class TestController {

    @ContentType('application/octet-stream')
    @Get('/stream')
    stream(@Res() res) {
        require('fs').createReadStream('someFile.dat').pipe(res);
    }

}
````

The example above does not work correctly, returns 404, unless we remove https://github.com/pleerock/routing-controllers/blob/master/src/driver/express/ExpressDriver.ts#L301 line.

**Comment by pleerock** [comment]
can you add `@OnUndefined(200)` where 200 is any status code you want?:

```ts
import {Get, JsonController, Res} from "routing-controllers";

@JsonController('/test')
export class TestController {

    @ContentType('application/octet-stream')
    @Get('/stream')
    @OnUndefined(200)
    stream(@Res() res) {
        require('fs').createReadStream('someFile.dat').pipe(res);
    }
```

}

**Comment by Luke265** [comment]
With `@OnUndefined(200)` returns 200, but the result is now empty. Possible duplicate of #24

**Comment by marshall007** [comment]
@pleerock it would probably make sense to allow the user to return a `Stream` from their controller method and if they do so, automatically pipe it to the response.

**Comment by pleerock** [comment]
> With @OnUndefined(200) returns 200, but the result is now empty.

this sounds strange, on undefined do not effect those things. Can you make debugging a bit?

> it would probably make sense to allow the user to return a Stream from their controller method and if they do so, automatically pipe it to the response.

yeah it would be very good to support that. Contributions are welcomed 😉

**Comment by marshall007** [comment]
@pleerock I created an issue for that. I'll try to get around to it soon.

**Comment by pleerock** [comment]
@marshall007 any updates?

**Comment by 19majkel94** [comment]
@pleerock 
Looks like @Luke265 has made a PR but abandoned it so I will close it and reimplement the feature with tests in new PR.
