### ISSUE TITLE
question: How pass TypeORM object to routing-controllers for serialization?

### ISSUE THREAD

**Issue by NoNameProvided** [pleerock/routing-controllers#181]
When I would like to send the down an entity with it's relations I used query builder to join the columns. But in easier cases it would be enough to simply send down the eager loaded relation, but serialization in routing-controllers seems to generate private prop for these.

So when I have the following relation
```ts
@ManyToMany(type => Category, category => category.users, {
    cascadeInsert: false,
    cascadeUpdate: false,
  })
  @JoinTable()
  categories: Promise<Category[]>;
```

and await it like this before sending down: 
```ts
let user = await getRepository<User>(User).findOneById(claims.sub});
await user.categories;
return user;
```

it will add the following to the serialized object:  
```json
"__categories__": [ { "id": 23, "otherProp": null }],
"__has_categories__": true,
```
Obviously it would be nice if it would be added as categories simply. 

I dont know what is the best way to do this? Await promises on object before sending them to class-transformer? Maybe add class-transformer an option to await Promises?

**Comment by pleerock** [comment]
> class-transformer an option to await Promises?

nooo that is too specific. 

Probably I can only suggest to develop a manual mechanizm of doing this thing. Too specific. Plus lazy relations are something experimental.

**Comment by NoNameProvided** [comment]
This, can be done with interceptors, would have been nicer if we can come up with some general solution for this.

**Comment by pleerock** [comment]
it such general solution would exist then it most probably will be part of class-transformer library
