### ISSUE TITLE
Should @BodyParam default to required?

### ISSUE THREAD

**Issue by subvertallchris** [pleerock/routing-controllers#185]
Taking a stab at rebuilding a Ruby/Grape API with Koa2 and this library, extremely happy that it exists. Thank you for your work!

Something I noticed is that that Params specified in a request function are not required by default. Reading this signature, I'd expect it to raise an error if any fields are missing in my POST:

```typescript
@Post('/buzz')
createSession(@BodyParam('foo') foo: string, @BodyParam('bar') bar: string, @BodyParam('baz') baz: string) { 
  // do something
}
```

I see I can add the `{ required: true }` option, but I feel like the less surprising default would be a closer to match to what the TS function signature describes, which is "everything is required." As it stands, the default forces us to treat each param as optional, so the TS signature does not accurately describe the input. Changing the default would make things safer and more trustworthy by default, which is a better user experience, IMO.

**Comment by BruceHem** [comment]
Exactly this's what I feel, e.g. The current user decorator also requires to put required: true. What if we could just use TS signature.

**Comment by marshall007** [comment]
@BruceHem there's no way to use the reflection metadata to determine whether a parameter is required or not. That information is not emitted by the TS compiler.

**Comment by pleerock** [comment]
Unfortunately as @marshall007 told we cannot use that information because typescript does not emit this information. We should ask typescript team to improve their reflection mechanizm and emit more data about code.

**Comment by subvertallchris** [comment]
No, that is not what I am suggesting, I know TypeScript won't allow it. What I am suggesting is a change to [this line](https://github.com/pleerock/routing-controllers/blob/master/src/decorator/BodyParam.ts#L17).

```typescript
export function BodyParam(name: string, options?: ParamOptions): Function {
    return function (object: Object, methodName: string, index: number) {
        getMetadataArgsStorage().params.push({
            // ...
            required: options ? options.required : true, // default to true, not false
            // ...
        });
    };
}
```

This would make the method signature match the library's defaults.

**Comment by IAMtheIAM** [comment]
New default option allows paramOptions to be required by default
```
useExpressServer(app, {

    defaults    : {
        paramOptions: {
            required: true // this means that all parameters (@BodyParam, @Param etc in Actions) are required by default
        }
    }
}
```

**Comment by NoNameProvided** [comment]
@IAMtheIAM, but it will be released in `0.7.3` so it cannot be used right now.

**Comment by 19majkel94** [comment]
@NoNameProvided it is released in 0.7.2, I've checked it.

**Comment by IAMtheIAM** [comment]
Yes confirmed, it is working in 0.7.2

**Comment by NoNameProvided** [comment]
Ahh ok, thanks for the correction, I must have mess up something during the update of my test project.
