### ISSUE TITLE
Questions regarding currentUserChecker and @CurrentUser decorator

### ISSUE THREAD

**Issue by BruceHem** [pleerock/routing-controllers#186]
// 1 - currentUserChecker 
```ts
export async function currentUserChecker(action: Action, value?: any) {}
```
I see in the sample there is a value param here, what is this value param for?

// 2 - CurrentUser
example here 
```ts
@CurrentUser({ required: true }) user: User
```
 ... isn't  { required: true } here redundant? since user is of type User. doesn't that mean it's required already?

**Comment by Diluka** [comment]
1. the type `CurrentUserChecker` only has one param ---- `action: Action`. See https://github.com/pleerock/routing-controllers/blob/master/src/CurrentUserChecker.ts
2. it's not redundant. `{ required: true }` means there must have a user, but `{ required: false }` means user is optional. For example, if you get user from authorization header, without this header, the user is null.

**Comment by BruceHem** [comment]
It's still redundant to me. But Never mind I'll implement my own user check

**Comment by pleerock** [comment]
no, its not redundant. Its not always you want your user to be required. For example you have `GET /posts/:id` and in this route logic you want to add "users who viewed this post". And you do `@CurrentUser()` without `required` and check if user is defined then add him to those who viewed the post and save a post.
