### ISSUE TITLE
How to get basic auth credentials?

### ISSUE THREAD

**Issue by Diluka** [pleerock/routing-controllers#188]
How to get the `user` and `pass` from url `http://user:pass@host:8080/p/a/t/h`?
There is only `/p/a/t/h` in `req.url` or `req.originalUrl`.

**Comment by BruceHem** [comment]
Please close this issue it's not related with routing controller.

**Comment by Diluka** [comment]
@BruceHem 
The request is `http://user:pass@host:8080/p/a/t/h`, and this part `user:pass@` is missing. There must be a reasonable explanation here.

**Comment by pleerock** [comment]
I didn't understand what is your problem. Routing-controllers does not change `req.url` or `req.originalUrl` anyhow.

**Comment by Diluka** [comment]
@pleerock 
I want to get this part `user:pass@` of `http://user:pass@host:8080/p/a/t/h`.
Where can I get it?

**Comment by pleerock** [comment]
refer express, you have express's request object. Use that to take it. See express docs how to get it
