### ISSUE TITLE
Can I extends controller class?

### ISSUE THREAD

**Issue by Diluka** [pleerock/routing-controllers#19]
I want to put same common code into abstract controller like a template. And a concrete controller can extend a abstract controller.

I don't want to copy codes, is there a way to avoid that?

**Comment by pleerock** [comment]
Extending controller generally is a bad idea. Controller uses decorators, and routes are hard coded there, you cannot change them via class inheritance. So, if you want to extend a controller class - do it, but you can only extract reused methods, you cannot do it for actions themself

**Comment by Diluka** [comment]
I understand

**Comment by AnimaMundi** [comment]
Would love to see the ability to use inheritance here with controllers!

**Comment by pleerock** [comment]
its not really a good idea, see my comment above

**Comment by AnimaMundi** [comment]
I've already seen your comment. It's a good idea, your implementation just doesn't allow for it, know the difference.

**Comment by pleerock** [comment]
implementation using decorators doesn't allow for it, and since we are talking about such implementation its not a good idea to think about it within this implementation at all.
