### ISSUE TITLE
@Body() not working 

### ISSUE THREAD

**Issue by sbacem** [pleerock/routing-controllers#190]
hello @pleerock 
I tried [https://github.com/pleerock/routing-controllers-express-demo](https://github.com/pleerock/routing-controllers-express-demo)
i can't get `category` value from `post` any idea how fixed it.
i use  node : v6.11.0

```
    @Post("/categories")
    category(@Body() category: Category): Category {
       console.log(category);
        return this.categoryRepository.save(category);
    }
```
result in console  
`{}`

**Comment by NoNameProvided** [comment]
Do you send your request with POST method to `http://localhost:3000/categories` with: `{"name": "SomeTestName" }` as raw data? It works for me this way.

**Comment by sbacem** [comment]
@NoNameProvided
Yes of course, this is my post 

![dev](https://user-images.githubusercontent.com/6381938/27529322-4e436710-5a54-11e7-91dd-4d2addd2d960.png)

**Comment by NoNameProvided** [comment]
You send your payload as form data, you should select `raw` and send the payload as 

```json
{
  "name": "book"
}
```

**Comment by sbacem** [comment]
Thanks very much @NoNameProvided 
select raw and JSON(application/json), it work.
