### ISSUE TITLE
Extending the HttpError class with custom response

### ISSUE THREAD

**Issue by mtziyo** [pleerock/routing-controllers#191]
I think this is more of a question rather than an issue,

what I am trying to do is extend the HttpError class to accept an object with additional parameters
something like below mentioned.

`export class CustomHttp extends HttpError {
    constructor(message: string, params: object, code: number) {
        super(400, message, params, code);
    }
}`

would like to know if possible?

**Comment by BruceHem** [comment]
Yes It's possible

**Comment by pleerock** [comment]
yes it is possible
