### ISSUE TITLE
How can I get the `Content-Type` of `response` in interceptor?

### ISSUE THREAD

**Issue by Diluka** [pleerock/routing-controllers#192]
How can I get the `Content-Type` of `response` in interceptor?
I tried `response.get("Content-Type")` and get `undefined`.

**Comment by NoNameProvided** [comment]
The first parameter for interceptors is an `Action`. You can get it from it as `action.request.headers[“Content-Type”]`. If it’s undefined it means it was not defined for the given request

**Comment by Diluka** [comment]
Not request, it's response

EL PSY CONGROO

在 2017年6月27日，下午3:28，Attila Oláh <notifications@github.com> 写道：

**Comment by NoNameProvided** [comment]
Then you can `action.response.headers[“Content-Type”] `

**Comment by Diluka** [comment]
@NoNameProvided `action.response.headers` is `undefined`

**Comment by pleerock** [comment]
probably because headers are set right before content is being sent. Probably the only way to get it is to use metadatas and underlying api to get it.

**Comment by Diluka** [comment]
So, some metadata like content type, setting before calling interceptors may be more reasonable. The only operation after intercepting is `send`. 
For now, if I set content type in interceptor, it will be override by decorators, right?

**Comment by pleerock** [comment]
I think yes

**Comment by 19majkel94** [comment]
@Diluka 
Please check if `action.headers` doesn't contain info collected with decorators like `@ContentType`.

**Comment by Diluka** [comment]
It has.

在 2017年8月8日，上午1:39，Michał Lytek <notifications@github.com> 写道：
