### ISSUE TITLE
Throwing Exceptions within catch clause of a promise

### ISSUE THREAD

**Issue by mlarsson** [pleerock/routing-controllers#197]
Can it be true that I am not able to use the predefined exceptions e.g. NotFoundError within a catch clause?

```
@Get('')
getResource() {
    getResourceAsPromiseFromSomewere()
    .then(...)
    .catch(() => {
        throw new NotFoundError('Some explaination');
    });
}
```

I would expect that the above will resolve in a 404 and the message:
```
{
  "name": "NotFoundError",
  "message": "Some explaination"
}
```

But instead I get a 404 with Content-type: text/html and content:
"Error at NotFoundError.HttpError [as constructor] (.../node_modules/routing-controllers/http-error/HttpError.js:27:23) at new NotFoundError (.../node_modules/routing-controllers/http-error/NotFoundError.js:20:28) at handleException (..my-file.js:33:29) at process._tickCallback (internal/process/next_tick.js:109:7)"

**Comment by 19majkel94** [comment]
The problem is that your `getResource()` action handler doesn't return the promise, so the routing-controllers executor doesn't wait for the `getResourceAsPromiseFromSomewere` promise and return 404 on undefined 😉

**Comment by 19majkel94** [comment]
I see no response from @mlarsson so I'm guessing that the problem is fixed - closing 😉

**Comment by mlarsson** [comment]
Hi Michał

I'm sorry I must have missed the notification on this one and didn't realize that you gave an answer. 

I checked my code and I actually do return the promise (I simply made a mistake when I posted the example). So I see this behavior even though I return the promise.

**Comment by NoNameProvided** [comment]
If your promise resolves with undefined, it still will generate a 404 response.

**Comment by 19majkel94** [comment]
> But instead I get a 404 with Content-type: text/html and content...
Have you got your controller marked as `@JsonController`? Looks like it's returning text because the action is not jsontyped.

**Comment by mlarsson** [comment]
It seems to work as expected when I put JsonController. Thank you for all your help :-)
