### ISSUE TITLE
Setting global middleware to run before request handling

### ISSUE THREAD

**Issue by mlarsson** [pleerock/routing-controllers#198]
I cannot find a way to register a global middleware that must run before request handling. It can be done if it is a middleware which I created myself and I use the "middlewares" option during creation of the server i.e. on "createExpressServer". But Lets say I want "express-jwt" to run before and I want to register it globally. Can this be done?

**Comment by NoNameProvided** [comment]
Try [Global Middlewares](https://github.com/pleerock/routing-controllers#global-middlewares)

**Comment by mlarsson** [comment]
I don't understand. How am I suppose to annotate a middleware that I didn't create myself? Did you read my whole post before answering?

**Comment by NoNameProvided** [comment]
Try this: https://github.com/pleerock/routing-controllers#use-exist-middleware

**Comment by mlarsson** [comment]
It is the combination I asking about: "registering a middleware which I **did not create** myself, which must run **before** request handling and **make it global**". If I'm following the doc. I can use app.use(...) but this will make it run **after** request handling. I also saw the note: "Alternatively, you can create a custom global middleware and simply delegate its execution to the compression module." but can it be true that this is the only solution? It seems a little clumsy.

**Comment by 19majkel94** [comment]
> If I'm following the doc. I can use app.use(...) but this will make it run after request handling.

```ts
app.use(jwt());
createExpressServer();
app.use(// after middleware);
```

**Comment by 19majkel94** [comment]
I think that's solved, so I'm closing this issue. @mlarsson feel free to reopen if you have more questions 😉
