### ISSUE TITLE
Proposal: response wrappers for success responses

### ISSUE THREAD

**Issue by adnan-kamili** [pleerock/routing-controllers#204]
In case of errors we can throw exceptions like NotFoundError etc. Similarly for success responses their could be wrappers which do common tasks like:

taken from Asp.Net Core:

```
// return response with 200 status code - current default
return Ok(user);  
```

```
// return response with 201 status code, add url (first param) to Location header
return Created($"/v1/users/{user.Id}", new { message = "User was created successfully!" });
```

```
// return empty response with 204 status code
return NoContent();
```

Using decorators like `@HttpCode(204)` for every overriding behaviour is sometimes overkill, it adds such a big stack of decorators for each controller action.

Currently to add location header for 201 response, one would need to create a middleware, but it's very common in rest api's should be handled at framework level.

**Comment by NoNameProvided** [comment]
You can use [interceptors](https://github.com/pleerock/routing-controllers#using-interceptors).

**Comment by adnan-kamili** [comment]
It's not about formatting response body, it's about support for REST compliant response status/headers out of the box, purpose of framework/library is to care for this common stuff.

**Comment by 19majkel94** [comment]
`routing-conrollers` is built on top of `express` framework. The main idea is to provide an abstraction over express and basic http-related things, so the action handler is the normal method like a service, which takes User object, id number and return entity from database. Injecting the params from request fields and returning response is happening under the hood, so you can easily create unit tests.

If you need some non standard things, like pipe filestream to response, you can use express features. Your 201 example:
```ts
response
  .status(201)
  .location(`/v1/users/${user.id}`)
  .send({ message: "User was created successfully!" });
```
And thanks to interceptor functionality and `routing-controllers` extensibility, you can create your own wrapper classes like `Created` or `NoContent` and transform it there to correct responses 😉

**Comment by pleerock** [comment]
@adnan-kamili what is your proposal here? As I understood you want to introduce functions like `Ok`, `Created`, `NoContent`? If yes, then answer is that its a bad idea. Because first we have decorators for same purpose which are better then function but less flexible, and second we have standard express API you can use to do what you want, e.g.

```ts
action(@Res() res: Response) {
    res.status = 201;
    res.location = ... etc
}

**Comment by adnan-kamili** [comment]
I am using koa and it actually breaks the symmetry of the code. It requires the explicit setting of headers:
```javascript
ctx.set("Location", `/v1/users/${user.id}`);
return { message: "user created successfully!" };
```

Maybe a decorator which expects a return statement from action something similar like:

return { body: {}, location:"" };

@Created()

**Comment by pleerock** [comment]
It does not break symmetry. Thats how you do what you want to do. I don't think routing-controllers shall provide any additional wrappers for such code

**Comment by 19majkel94** [comment]
`res.status` is a function 😉 
```ts
res.status(404).send("Not found!");
```

**Comment by aeremin** [comment]
Thanks a lot! I misunderstood what is actual type of res being injected.
