### ISSUE TITLE
Nested routes: delegate to another controller

### ISSUE THREAD

**Issue by bsitruk** [pleerock/routing-controllers#207]
Hi !
Is there anyway to use different controllers for nested routes ?

For instance, I would use a `V1Controller` to handle the `/v1` route,
and another `UserController` to process the `/v1/users` route.
So that, the `V1Controller` would delegate the `/users` path to `UserController`.

If not yet possible, would it be a good idea to implement this ?

Thanks !

**Comment by 19majkel94** [comment]
```ts
@JsonController("/v1/users")
export class UserController {
}

@JsonController("/v1")
export class V1Controller {
}
```

**Comment by bsitruk** [comment]
Thanks for your help.
Not quite what I was looking for though.

The idea was not to have to repeat the '/v1' path more than once.

In express:
app.use('/v1', V1Controller);
V1Controller.use('/users', UserController);

**Comment by 19majkel94** [comment]
I would like to see it as a declarative API:
```ts
@JsonController("/v1")
@MountController("/users", UserController)
export class V1Controller {
}
```
But what should happen if in `UserController` we do this?
```ts
@JsonController("/users")
export class UserController {
}
```
Maybe we should just mount controllers:
```ts
@JsonController("/v1")
@MountControllers([UserController, AttachmentController])
export class V1Controller {
}
```
So the `@JsonController("/users")` would be appended to the mounted path.

But then how the `routing-controller` can distinguish on bootstraping and decorator evaluation, which controller is mounted to root and which to other controller? @pleerock any ideas? 😉

**Comment by pleerock** [comment]
> The idea was not to have to repeat the '/v1' path more than once.

I don't have words to comment this 🙊 

Even `JsonController("/v1")` I find useless. Don't afraid repeat routes, it makes them explicit and easy to maintain and work with.

And no need to overcomplicate things.

**Comment by bsitruk** [comment]
I think it has a use case: say you want reuse the same controller for different routes: '/v1/users' and 'v2/users' both call the same UserController.

**Comment by nelson-ks** [comment]
Sorry to bring up an old post but I found this is useful in case of nested resources, especially when:
`
/users/<user_id>/posts
/tags/<tag_id>/posts
`

We can reuse the posts controller by letting the users & tags controller to attach their own middleware to inject the users/tags object, which could be an implementation of interface PostCollection, and mount the posts controller under its path

In this case the posts controller don't need the knowledge about its parent collection.

For sake of readability, we can use DI for the mounting, and the composition root will tell the relationship between the resources. While this is not a beauty annotation way to represent the path, it give a high level understanding of how the resources are composed. IMO, this may be preferred when one has a large api set.
