### ISSUE TITLE
@QueryParam enum support

### ISSUE THREAD

**Issue by gempain** [pleerock/routing-controllers#208]
Hello,

`@QueryParam('type') type: MyEnum` will always set `type` to `NaN`. Otherwise, doing `@QueryParam('type', {type: OperationType}) type: OperationType` throws an error, since enums do not have constructors.

My current workaround is:

```typescript
@UseBefore(RequestValidationUtils.isEnumMiddleware('type', MyEnum))
get(...)
```
and
```typescript
import {Validator} from "class-validator";

export class RequestValidationUtils {

  public static isEnumMiddleware(queryParam, entity): Function {
    return (req, res, next): void => {
      const validator: Validator = new Validator();
      const queryParamValue = req.query[queryParam];
      if (!queryParamValue || validator.isEnum(req.query[queryParam], entity)) {
        next();
      } else {
        res.status(400).send('Bad request');
      }
    };
  }
}
```

Thanks for the amazing work !

**Comment by pleerock** [comment]
PRs are accepted for this feature

**Comment by 19majkel94** [comment]
Can you show how the `MyEnum` type looks in your code? Is this normal TS enum? As far as I know there is a problem with reflection of this kind of types so `class-transformer` don't now how to map query param value to JS object or string or number.

**Comment by 19majkel94** [comment]
`@QueryParam('name')` decorator is really hard in implementing features with validation and others - we won't develop new features for it, so in order to have validation on query params please take a look on #270 - the PR do the casting to type so you can declare a class with validation decorators 😉

**Comment by gempain** [comment]
Sorry for the delay ! My enum is a string enum:

```
enum MyEnum {
  A = <any>'a',
  B = <any>'b',
}
```

which produces a JS enum like so:
```
{
  'a': 'A',
  'A': 'a',
  'b': 'B',
  'B': 'b'
}
```

I made a PR a few weeks ago that added support for string enums to the `@Enum` decorator.

**Comment by 19majkel94** [comment]
> To be reopened ?

Nope, TS 2.4 string enums works in runtime just like the old enums, nothing changed, just no need for "<any>" casting.

**Comment by gempain** [comment]
Right, but why close this issue since it is tagged as "new-feature" ? Will you still accept PRs ?

**Comment by 19majkel94** [comment]
String enums have reflected types as String, so now it should be normalized to a string, not as a NaN (normal enums are numbers in runtime). 

If you need validator on query param, you should use `@QueryParams()` decorator, declare a class for it and decorate with `@IsEnum` and other class-validator decorators.

**Comment by gempain** [comment]
Sweet, I didn't know there was an `@QueryParams()` feature (I see it now in the docs :) ). Thanks for the solution !
