### ISSUE TITLE
Signature Mismatch in `MiddlewareInterface`

### ISSUE THREAD

**Issue by JD-Robbs** [pleerock/routing-controllers#21]
Consider the following code (note the Request/Response type hints):

```
export class MyMiddleware implements MiddlewareInterface {
    use(request: Request, response: Response, next?: Function): any {
```

Compiling throws the following error:

```
error TS2420: Class 'MyMiddleware' incorrectly implements interface 'MiddlewareInterface'.
  Types of property 'use' are incompatible.
    Type '(request: Request, response: Response, next?: Function) => any' is not assignable to type '{ (request: any, response: any, next?: (err?: any) => any): any; (context: any, next: (err?: any)...'.
      Types of parameters 'response' and 'next' are incompatible.
        Type '(err?: any) => Promise<any>' is not assignable to type 'Response'.
          Property 'status' is missing in type '(err?: any) => Promise<any>'.
```

This, however, works:

```
export class MyMiddleware implements MiddlewareInterface {
    use(request: any, response: any, next?: Function): any {
```

I tracked the issue to the second (Koa) signature in `MiddlewareInterface` (removing it fixes the above but, obviously, won't make Koa happy).  It looks like my code makes the TypeScript compiler think I'm trying to implement the second signature.

While I tried changing/adding signatures in `MiddlewareInterface`, I couldn't get it to compile.

**Comment by pleerock** [comment]
Not sure what is possible there. I know about this issue with typescript, one solution can be if we create two separate interfaces `KoaMiddlewareInterface` and `ExpressMiddlewareInterface` instead of `MiddlewareInterface`. If you can come to solution with `MiddlewareInterface` please let me know

**Comment by JD-Robbs** [comment]
If I can work out a way to keep it all in one interface, I'll let you know.  I'll take another look and maybe check if anyone on StackOverlow has any ideas.

**Comment by marshall007** [comment]
@JD-Robbs I was able to get it to compile by overloading the method on my custom class with the more generic signature:

```ts
@Middleware()
export class CustomerHeader implements MiddlewareInterface {

  use(request: any, response: any, next?: (err?: any) => any): any;
  use(request: Request, response: Response, next?: NextFunction): any {
    // ...
    next();
  }

}
```

@pleerock I think if you annotate `MiddlewareInterface` with the additional overloads it should allow users to implement the method with or without typed parameters.

**Comment by pleerock** [comment]
new middleware interface signatures are being added in #119

**Comment by pleerock** [comment]
middlewares now have separate signatures in 0.7.0
