### ISSUE TITLE
controllers not loading if used with pkg

### ISSUE THREAD

**Issue by adnan-kamili** [pleerock/routing-controllers#211]
I tried to compile the project to a binary using:

https://github.com/zeit/pkg

The controllers are get compiled and packaged into the binary but not loading:
` controllers: [__dirname + "/controllers/*.js"],`

hence all requests are return with 404 Not Found Error.

In package.json pkg config is:

```
"pkg": {
    "scripts": "build/**/*.js",
    "targets": [
      "node8-win-x64"
    ]
  },
```

Any idea how to fix this?

**Comment by 19majkel94** [comment]
> During packaging process pkg parses your sources, detects calls to require, traverses the dependencies of your project and includes them into executable. In most cases you don't need to specify anything manually. However your code may have require(variable) calls (so called non-literal argument to require) or use non-javascript files (for example views, css, images etc). Such cases are not handled by pkg. So you must specify the files - scripts and assets - manually in a config. It is recommended to use package.json's pkg property.
"pkg": {
    "scripts": "build/**/*.js",
    "assets": "views/**/*"
  }
Just be sure to call pkg package.json or pkg . to make use of scripts and assets entries.

Dynamically loaded controllers are like assets - you have to copy them manually or load explicitly the controllers [like here](https://github.com/pleerock/routing-controllers#prefix-all-controllers-routes).

**Comment by adnan-kamili** [comment]
I tried passing them as assets too, so that source files are added as such, but still it didn't work., Ideally it should as pkg adds the source files to the snapshot filesystem frow where they can be accessed

**Comment by pleerock** [comment]
its not routing-controllers issue, this issue is about how you handle your build with pkg. Simply make sure to specify correct path to `controllers: [...]` which really exist in your final build.
