### ISSUE TITLE
Allow to create custom drivers

### ISSUE THREAD

**Issue by shlomiassaf** [pleerock/routing-controllers#212]
The types `createExecutor`, `Driver`, `BaseDriver`, `ExpressDriver` and `KoaDriver` are not exposed by the library.

This make it hard to extend the library for custom use cases.

Is there a reason why they are not exposed? this kind of library abstract away most of the server's code but sometimes extensibility is required...

Can you expose them?

Thanks.

**Comment by pleerock** [comment]
Send PR with what you need to be exported and I'll merge it.
