### ISSUE TITLE
Returning empty

### ISSUE THREAD

**Issue by jossiwolf** [pleerock/routing-controllers#224]
Hey,
I'm wondering how return an empty response?

I set the status code to 204, but when using `return;`, a "could not get /..." page is automatically rendered. How do I avoid this?

```typescript
@Patch("/status")
@HttpCode(204)
updateUserStatus() {
    return;
}
```

**Comment by NoNameProvided** [comment]
In JS `undefined` is the un-initalized value. So when a route returns undefined it will be treated as `404`. To return with a `204 No Content` response you have to return with `null` from your handler.

**Comment by jossiwolf** [comment]
Ah. Didn't think of that.
Thank you so much!

**Comment by pleerock** [comment]
Or you can do:

```ts
@Patch("/status")
@OnUndefined(204)
updateUserStatus() {
    return;
}
```
