### ISSUE TITLE
how to return a binary file response

### ISSUE THREAD

**Issue by adnan-kamili** [pleerock/routing-controllers#228]
I am returning a binary file as a response, but it is returned as a json:

```javascript
{
    "0": 37,
    "1": 132,
    "2": 114,
    "3": 119,
    "4": 150,
    "5": 148,
    "6": 170,
    "7": 246,
    "8": 138,
    ...
}
```
I am using `@Controller` decorator and tried setting the content-type header but content-type is set to `application/json` even if I set it explicitly to `application/octet-stream` but still it didn't work:

```javascript
@Get("/:id/product.dat") 
@Header("Content-type", "application/octet-stream") // didn't work
async getProductFile( @Ctx() ctx: any, @Param("id") id: number) {
        ...
        const productFileDat: Buffer = hexDecode(productFile);
        ctx.set("Content-Type", "application/octet-stream");  // didn't work either
        ctx.attachment("Product.dat");
        return productFileDat;
 }
```

**Comment by 19majkel94** [comment]
Currently you have to use normal koa `ctx` way (in express use `res.send()` method).
There will be a support for returning streams or binary files, etc.

**Comment by fabiob** [comment]
@19majkel94, the `aws-sdk` types declare the body of a (possibly) binary request as:

```typescript
export type Body = Buffer|Uint8Array|Blob|string|Readable;
```

Source: https://github.com/aws/aws-sdk-js/blob/872104e770bb215f1324c26a2fe696dac1367db0/clients/s3.d.ts#L747

**Comment by 19majkel94** [comment]
@fabiob 
In #285 I've added support for streams (Readable) Buffer and UintArray. Blob is browser-only.
However I'm not sure if this is correct way for sending binary data as I'm not able to debug if the send bytes are correct or not, could you check, please?

**Comment by acuntex** [comment]
> Currently you have to use normal koa ctx way (in express use res.send() method).
> There will be a support for returning streams or binary files, etc.

Could you explain this?

Maybe I'm doing something wrong:
```
    @Get("/getFile")
    public async getFile(@Ctx() context: Context, @QueryParam("url") url: string)
    {
        let stream = await this.getStreamFromUrlAsync(url);
        if (!stream)
            return;
        context.type = "image/jpeg";
        context.body = stream.toBuffer();
    }
```
This way I always get:
`{"name":"NotFoundError","stack":"Error\n    at NotFoundError.HttpError [as constructor] (/path/node_modules/routing-controllers/http-error/HttpError.js:27:23)\n    at new NotFoundError (/path/node_modules/routing-controllers/http-error/NotFoundError.js:20:28)\n    at KoaDriver.handleSuccess (/path/node_modules/routing-controllers/driver/koa/KoaDriver.js:277:33)\n    at /path/node_modules/routing-controllers/RoutingControllers.js:128:61\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)"}`

**Comment by 19majkel94** [comment]
Please wait for #285 and #286.
