### ISSUE TITLE
how to enable class sanitizer

### ISSUE THREAD

**Issue by adnan-kamili** [pleerock/routing-controllers#230]
I tried sanitizers from 

https://github.com/pleerock/class-sanitizer

for request body but they don't work, most probably because sanitizer is not invoked automatically. Is it possible to enable the same.

**Comment by 19majkel94** [comment]
Currently there is no integration like with `class-validator`. You have to call sanitize function manually in your controller or create a custom middleware that will do that for you.

**Comment by pleerock** [comment]
I would like to merge class-sanitizer into class-validator in the future. However I don't have time on it yet. I think this issue can be closed and instead issue in class-validator must be created with request to merge it with class-sanitizer.
