### ISSUE TITLE
Validating incorrect values sent on Post ?

### ISSUE THREAD

**Issue by appsolutegeek** [pleerock/routing-controllers#232]
Hi,

I am using the class-validator that is enabled by default and i am decorating some of my incoming models with decorators so to throw an error i..e

`       @IsNotEmpty()`

and this works great but if the calling sends in additional properties that don't exist in my model they actually get added. Here is my controller method

```
    @Post("/create")
    createTransaction(@Body() depositTranRequest: DepositTranRequest) {
```

So hence DepositTranRequest doesn't have a property called "test" on it but if I call into it using a rest client and as long as the rest of the validation passes that it arrives in my controller as if its valid. But the property test does not exist in the model so it should really fail it.

What are my options here ? Is there something I can do either with class-validator or something else?

Thanks in advance.

**Comment by appsolutegeek** [comment]
I also added the class trasnform npm and added this line

            classTransformer: true,

but still the depositTranRequest has items that don't exist in the object type.

**Comment by 19majkel94** [comment]
Unfortunately, `class-transformer` only creates instance from plain object/JSON, that you can use prototypes methods and get info from validation decorators. It doesn't perform type validation (if prop1 is string, prop2 boolean, etc.) so it also doesn't trim unnecessary properties.

But what is the problem with additional properties? You return the received body as a response? You should treat all params/body objects as a immutable, read only objects and creates new ones based on the data from them.

**Comment by appsolutegeek** [comment]
Thanks, yes finally I am ignoring any params being sent in that are not in the actually model and I am mapping a response based on this so any non valid values get filtered out.

**Comment by NoNameProvided** [comment]
This has a tracking ticket here: https://github.com/pleerock/routing-controllers/issues/200 and here https://github.com/pleerock/class-transformer/issues/74
