### ISSUE TITLE
Using inversify, constructor is called twice on controller when instantiated each call

### ISSUE THREAD

**Issue by appsolutegeek** [pleerock/routing-controllers#239]
Hi,

I am using inversify with routing controllers but i put a console.log into the constructor of my JsonController and it is being called twice.

I have the decorator @injectable() . on the Controller and its being registered inside the container using bind. I had to use toSelf otherwise it throws an error.

        container.bind(DepositController).toSelf();

I am also calling useContainer, and passing in the container.

Everytime i call into the controller using a rest client it calls the contructor twice.

Anyone got this issue ?

**Comment by 19majkel94** [comment]
I would recommend you to use [TypeDI](https://github.com/pleerock/typedi) which has seamless integration with `routing-controllers` and other libs made by pleerock 😉 

But I will leave this issue opened, maybe there is a person which could help you with inversify configuration.

**Comment by appsolutegeek** [comment]
Yes, I think if I have to I can go to TypeDI, I did like how inversify works and seems a really well supported library. I would like to get it to work with routing controllers if possible.

**Comment by Genert** [comment]
This issue still persists.
