### ISSUE TITLE
[Solved] 0.7.1 Typescript Error For Container

### ISSUE THREAD

**Issue by AnthoniG** [pleerock/routing-controllers#245]
Hello,

I am just trying out Routing-Controllers having seen it in a Medium posting. So far I am loving what I am seeing. So much easier to set up my routes in Express.

However, I am having trouble with Typescript when I try and use Container for dependency injection.

Here is the error :-
`src/config/Express.ts(37,7): error TS2345: Argument of type '{ cors: true; controllers: typeof Index[]; container: typeof Container; }' is not assignable to parameter of type 'RoutingContr
ollersOptions | undefined'.
  Object literal may only specify known properties, and 'container' does not exist in type 'RoutingControllersOptions | undefined'.
`

Here is my code :-
`useExpressServer(this.app, {
      cors: true,
      controllers: [Index],
      container: Container
    });`

It does not like having the container in there. If I look at `RoutingControllersOptions.d.ts` then there is actually no container specified

Is this some kind of mix up with the examples and the documentation?
How do I get it to use the container for DI ?

Regards
Anthoni

**Comment by 19majkel94** [comment]
https://github.com/pleerock/routing-controllers#using-di-container
