### ISSUE TITLE
Cannot find name 'Promise'

### ISSUE THREAD

**Issue by migace** [pleerock/routing-controllers#25]
Hi, 

it's amazing library, which can help me in my project. Unfortunately, I've problem with correct compilation by tsc. 
I receive this error: 
node_modules/routing-controllers/middleware/MiddlewareInterface.d.ts(14,60): error TS2304: Cannot find name 'Promise'.

Is it problem with this lib or it's my problem with incorrect configuration ?

**Comment by JD-Robbs** [comment]
As long as your version of Node supports most ES6 features, you can easily solve this by changing TypeScript's compilation target to `es6` in your `tsconfig.json`: `{"compilerOptions": {"target": "es6"}}`.

**Comment by pleerock** [comment]
@migace you can follow JD-Robbs, or if you still want to use es5 target you can simply install es6-shim throw the typings, .e.g `typings install dt~es6-shim --save --global `

**Comment by migace** [comment]
Hi guys, 

I came back from work and tried your tips... It's work. Thank very much for interesting and so fast response. It's nice and I am very happy. It's power of Open Source 👍 Thanks again :)
