### ISSUE TITLE
How to add SSL and run HTTPS server

### ISSUE THREAD

**Issue by telvin** [pleerock/routing-controllers#253]
Default, I use useExpressServer to install middleware and can start the server with a custom port

```
let app = express();
let serverOptions:any = {
        controllers: [baseDir + "/controllers/*/*{.js,.ts}"],
        middlewares: [baseDir + "/controllers/*/middleware/*{.js,.ts}"],
    }
app = useExpressServer(app, serverOptions);
app.listen(9000); // httpServer
```

It works fine.
However, I want to run a HTTPS server (with available SSL cert). I made it as below:

```
var https = require('https');
let credentials = {key: privateKey, cert: certificate, ca: [CACert]};
serverOptions = {...credentials, ...serverOptions}
var httpsServer = https.createServer(serverOptions, app);
httpsServer.listen(9000);
```

After running the server, I make the request to it, it returns error 404 not found (the HTTPS URL is working, but it cannot find the defined routing) I guess it did not install the middlediware after all. I think I misconfigured it because I was using the method `listen` for `httpsServer` instead of express app variable.

I cannot find any example to start https by using this method `useExpressServer`. Please give some advise.

**Comment by telvin** [comment]
It's an silly error and the server cannot start. There is nothing wrong with the configuration. I closed the issue.

**Comment by MikeDabrowski** [comment]
I also want to create https server. I created it alongside the regular (createExpressServer) but any request returns NoHttpResponseException

```javascript
    this._app = this.createServer(); // returns app created with createExpressServer
    this._app.listen(7999, () => {
      console.log('Server started on port 7999');
    });

    const credentials = {
      key, cert
    };
    this._server = https.createServer({...credentials}, this._app);
    this._server.listen(9999, () => {
      console.log('HTTPS Server started on port 9999');
    });
```

**Comment by NoNameProvided** [comment]
@MikeDabrowski use `useExpressServer` instead.

**Comment by MikeDabrowski** [comment]
@NoNameProvided  In what order?
`https.createServer` needs express server as second param, so does `userExpressServer`. Should I do it this way?
```js
let app = express();
let secure = https.createServer(options, app);
let rcapp = useExpressServer(rcOptions, secure); 
```

**Comment by MikeDabrowski** [comment]
Ok I got it:

```js
// create express server as usual either createExpressServer or useExpressServer
this.app = createExpressServer(someOptions);
// configure  other middlewares or swaggers as on usually on app
// create https server
this.app = https.createServer({key,cert}, this.app);
this.app.listen(433,()=>console.log('https server on 433'));
```

so in my first attempt I started express app prior creating https server. If you want http then `http.createServer(...)` before `https.createServer(...)`.
