### ISSUE TITLE
async action with Authorized return 404

### ISSUE THREAD

**Issue by yaoyel** [pleerock/routing-controllers#262]
async action with Authorized return 404

**Comment by yaoyel** [comment]
async action with Authorized return 404 where server is koa
express is ok

**Comment by 19majkel94** [comment]
Closing as a duplicate of https://github.com/pleerock/routing-controllers/issues/240.

**Comment by xujif** [comment]
this bug still exists at 0.7.2

**Comment by 19majkel94** [comment]
I've checked this:
https://github.com/pleerock/routing-controllers/issues/240#issuecomment-320595832
And it fails on 0.7.1 but works on 0.7.2. 

@xujif 
Please open a new issue if you claim that is not fixed. Create a minimal reproducible use case.

**Comment by xujif** [comment]
#282
