### ISSUE TITLE
CORS does not work with Dynamic / Async origin

### ISSUE THREAD

**Issue by IAMtheIAM** [pleerock/routing-controllers#278]
This module will not accept anything accept `true` or a valid cors object because of this code in ExpressDriver.ts file around line 40:

```
    initialize() {
        if (this.cors) {
            const cors = require("cors");
            if (this.cors === true) {
                this.express.use(cors());
            } else {
                this.express.use(cors(this.cors));
            }
        }
    }
```

However, this prevents the ability of having a whitelist of domains, since the official usage is to create a function which is called at runtime with the request origin and then the callback sends the true/false flag.

From the [CORS Docs](https://github.com/expressjs/cors#configuring-cors-w-dynamic-origin):

Configuring CORS w/ Dynamic Origin
```
var whitelist = ['http://example1.com', 'http://example2.com']
var corsOptions = {
  origin: function (origin, callback) {
    if (whitelist.indexOf(origin) !== -1) {
      callback(null, true)
    } else {
      callback(new Error('Not allowed by CORS'))
    }
  }
}

app.get('/products/:id', cors(corsOptions), function (req, res, next) {
  res.json({msg: 'This is CORS-enabled for a whitelisted domain.'})
})
```

Configuring CORS Asynchronously
```
var whitelist = ['http://example1.com', 'http://example2.com']
var corsOptionsDelegate = function (req, callback) {
  var corsOptions;
  if (whitelist.indexOf(req.header('Origin')) !== -1) {
    corsOptions = { origin: true } // reflect (enable) the requested origin in the CORS response
  }else{
    corsOptions = { origin: false } // disable CORS for this request
  }
  callback(null, corsOptions) // callback expects two parameters: error and options
}

app.get('/products/:id', cors(corsOptionsDelegate), function (req, res, next) {
  res.json({msg: 'This is CORS-enabled for a whitelisted domain.'})
})
```
Using either of these functions and loading any route from localhost results in response header `Access-Control-Allow-Origin:*` however, localhost is not in the whitelist, so it should be denied access.
It seems to not run the function correctly.

I propose to allow routing-controllers to work with an array of whitelisted origins.

Also, the current docs here on github do not mention Enabling CORS, but the npm package Readme does, so that should be updated.

**Comment by 19majkel94** [comment]
> Also, the current docs here on github do not mention Enabling CORS, but the npm package Readme does, so that should be updated.

https://github.com/pleerock/routing-controllers#enable-cors

**Comment by 19majkel94** [comment]
I don't understand, `corsOptionsDelegate` is a valid cors object config that can be passed to `createExpressServer` options, right? So what is the issue?

**Comment by IAMtheIAM** [comment]
Ok let me try to explain. 

I set my corsOptions to this

```
var whitelist = ['http://localhost', 'http://127.0.0.1'];
var corsOptions = function(req, callback) {
    var corsOptions;

    var originIsWhitelisted = whitelist.indexOf(req.header('Origin')) !== -1
    if (originIsWhitelisted) {
        corsOptions = { origin: true } // reflect (enable) the requested origin in the CORS response
        callback(null, corsOptions) // callback expects two parameters: error and options
    } else {
        corsOptions = { origin: false } // disable CORS for this request
        callback('WARNING: CORS Origin Not Allowed', corsOptions)
    }
}
```
When I request the page, the Response Headers is `Access-Control-Allow-Origin:*` However, instead of loading the page, it outputs the error message `WARNING: CORS Origin Not Allowed`

So it is not setting the access control header properly, and its calling the error callback even when loading the page from a whitelisted domain.

**Comment by 19majkel94** [comment]
The problem is with your `corsOptionsDelagate` function logic if it calls callback with error when it should. I don't see here any routing-controllers fault.

**Comment by IAMtheIAM** [comment]
OK, although I copied this function directly from CORS documentation and still doesnt work. Do you have any working example with array whitelist of CORS domains, like CORS docs says is possible?

**Comment by IAMtheIAM** [comment]
You're right, the problem is not with routing-controllers, its with CORS npm module, I'm closing this.

**Comment by NoNameProvided** [comment]
@IAMtheIAM Browsers will always send an `OPTION` request to cross-origin domains, so you can easily implement CORS however you like as a before middleware: 

```ts
import { Middleware, ExpressMiddlewareInterface } from 'routing-controllers';
import { NextFunction, Request, Response } from 'express';
import * as debug from 'debug';

@Middleware({ type: 'before' })
export class CorsMiddleware implements ExpressMiddlewareInterface { // interface implementation is optional
  private logger: debug.IDebugger = debug('pick:middleware:CorsMiddleware');

  public use(req: Request, res: Response, next?: NextFunction): any {
    this.logger(`Setting Access-Control-Allow-Origin headers to ${req.get('origin')}`);
    res.header('Access-Control-Allow-Origin', `${req.get('origin')}`);
    res.header('Access-Control-Allow-Credentials', `true`);
    res.header('Access-Control-Allow-Methods', 'GET,PUT,POST,DELETE,OPTIONS');
    res.header('Access-Control-Allow-Headers',
      'Content-Type, Authorization, Content-Length, X-Requested-With, Access-Control-Allow-Credentials');

    if (req.method === 'OPTIONS') {
      res.sendStatus(200);
      res.end();
    } else {
      next();
    }
  }

}
```

**Comment by IAMtheIAM** [comment]
@NoNameProvided Thanks I will check that implementation out
