### ISSUE TITLE
Avoid global state

### ISSUE THREAD

**Issue by Strate** [pleerock/routing-controllers#29]
As for me, having global state like this:

```
import "./SomeController" // import result affects as a global variable
let app = createExpressServer() // express server implicitly use "SomeController"
```

is not a good idea, because is handles like global variables. For example, this requries to clear metadata storage before each functional test. I think it could be better, if you made this opt-in, and add ability to explicit pass controllers, interceptors and other citizens to `createExpressServer`:

```
import SomeController from "./SomeController"
import SomeInterceptor from "./SomeInterceptor"
let app = createExpressServer(
  SomeController,
  SomeInterceptor
)
```

or somehow else. What do you think about it?

**Comment by pleerock** [comment]
I don't think its possible to avoid a global state when using decorators. So, in any cases decorators will register controllers in a global place. The only thing can be done, is to restrict controllers that needs to be registered in the express by providing a list of controllers implicitly, as you pointed out in the example.

[Here](https://github.com/pleerock/routing-controllers/blob/master/src/RoutingControllerExecutor.ts#L41) I already have a method that will register only controllers from the list of given classes. But ** classes** argument is not used yet, need to finish this part by sending a list of classes to `registerController` method [here](https://github.com/pleerock/routing-controllers/blob/master/src/index.ts#L92). [Here](https://github.com/pleerock/routing-controllers/blob/master/src/index.ts#L55) `importClassesFromDirectories` should return a list of classes to be registered. These classes needs to be send to the `registerController` method and everything should work I guess. I hadn't time to finish this part, but it definitely can be done easily. Try to do it, if no I'll do it later when I get more free time.

**Comment by Strate** [comment]
Global state for decorators can be avoided, if metadata information will stores inside class function (for example in `$metadata` or `$reflection`) property.
Thank you for that points, I'll check that.

**Comment by 19majkel94** [comment]
I like the way it's done in TypeORM:
```typescript
const options: CreateConnectionOptions = {
    // ... other options
    entities: [Photo, PhotoMetadata, Author, Album]
};
```
It could look here like this:
```typescript
let app = createExpressServer({
     controllers: [UserController, SampleController]
});
```
Now only dir with glob strings are supported:
```typescript
let app = createExpressServer({
     controllers: [__dirname + "/../controllers/*.js"]
});
```

**Comment by pleerock** [comment]
@19majkel94 we can add this feature too I think

**Comment by Strate** [comment]
I suggest you to use `Reflect` to store metadata.

**Comment by pleerock** [comment]
Im going to close this. @19majkel94 specifying `controllers` will be supported in `0.7.0`. Regarding to storing metadata - I'll left it as it is. No matter if its saved in exported variable or Reflect - it will be global in any cases.
