### ISSUE TITLE
@Authorized in version 0.7.2 stilll return 404.

### ISSUE THREAD

**Issue by Penggggg** [pleerock/routing-controllers#294]
happen:

       use Koa2 **async** controller with **async** authorizationChecker, still return a 404 in **@Authorized( )** decorator.

version:

       typescript: 2.4.2
       node: 7.6.0
       koa: 2.3.0
       routing-controllers: 0.7.2
       reflect0metadata: 0.1.10

code:

``` 
function sleep( time ) {
          return new Promise(( ok ,noOK ) => {
                  setTimeout(( ) => {
                        console.log('ok')
                        ok( );
                   }, time );
            })
}

@JsonController('/users')
export class UserCtrl {

  @Get('/')
  @Authorized( )
  async getAll(  ) {
        await sleep( 1000 );
        return "hahah" // serve return a 404 instead of ‘hahah’
  }
}

const app = new Koa( );
useKoaServer( app, {
  defaults: {
    paramOptions: {
      required: true
    }
  },
  authorizationChecker,
  routePrefix: '/api',
  controllers: [ UserCtrl ]
});
app.listen( 4000 );

async function authorizationChecker( action: Action, roles: string[]) {
  console.log('i am authorizationChecker')
  await sleep( 1000 );
  return true;
}

```

**Comment by 19majkel94** [comment]
Again - cannot reproduce:
```ts
import { JsonController, Get, Authorized, useKoaServer, Action } from "routing-controllers";
import * as Koa from "koa";

function sleep(time: number) {
    return new Promise((ok, noOK) => {
        setTimeout(() => {
            console.log("ok");
            ok();
        }, time);
    });
}

@JsonController("/users")
export class UserCtrl {
    @Get("/")
    @Authorized()
    async getAll() {
        await sleep(1000);
        return "hahah"; // serve return a 404 instead of ‘hahah’
    }
}

async function authorizationChecker(action: Action, roles: string[]) {
    console.log("i am authorizationChecker");
    await sleep(1000);
    return true;
}

const app = new Koa();
useKoaServer(app, {
    defaults: {
        paramOptions: {
            required: true,
        },
    },
    authorizationChecker,
    routePrefix: "/api",
    controllers: [UserCtrl],
});
app.listen(4000, () => console.log("listening 4000"));
```
package-lock.json:
```
"routing-controllers": {
      "version": "0.7.2",
      "resolved": "https://registry.npmjs.org/routing-controllers/-/routing-controllers-0.7.2.tgz",
      "integrity": "sha1-rOEUUBNJPPFCFPsTDsTwiGa8zts=",
```

**Comment by martine777** [comment]
i got the same issue, controller method execute properly without authorizationChecker, when using authorizationChecker,i got the 404 .

**Comment by 19majkel94** [comment]
@martine777 
Please post minimal code sample to make me able to reproduce the issue.
Minimal means like the sample above, not a half of your app 😉

**Comment by martine777** [comment]
@JsonController('/crud')
export class CrudController {
//CrudController.ts
    @Get("/:modelName")
    // @Authorized(PermissionClaims.createUser)
    async listAll( @Param("modelName") modelName: string, @Ctx() ctx) {
       
         const temp3 = await new Promise((resolve, reject)=>{
             setTimeout(function() {
                 resolve("aaaa");
             }, 1000);
         });
         return {status: 'ok', data: temp3};
    }

**Comment by 19majkel94** [comment]
Code sample is a "copy-paste and run", not the fragment of your code that force me to write by myself the bootstrap and the authChecker...

**Comment by martine777** [comment]
@JsonController('/crud')
export class CrudController {

    @Get("/:modelName")
     @Authorized()
    async listAll( @Param("modelName") modelName: string, @Ctx() ctx) {
         const temp3 = await new Promise((resolve, reject)=>{
             setTimeout(function() {
                 resolve("aaaa");
             }, 1000);
         });
         return {status: 'ok', data: temp3};
    }
   
}

**Comment by martine777** [comment]
const app = createKoaServer({
    routePrefix: "/api",
    defaultErrorHandler: false,
    classTransformer: true,
    authorizationChecker: async (action: Action, claims: string[]) => {
        console.log('claims...', claims);
        const verifyJwt = jwt(appOptions.jwt).unless({
            path: 
            ["/api/noUse", /^\/api\/auth/]
        });
        
        if (1 == 1) {return Promise.resolve(true) };
        
    },
    controllers: [__dirname + "/ctrl/*.js"],
    middlewares: [CustomErrorHandler]
});

**Comment by martine777** [comment]
Middleware({ type: "before" })
export class CustomErrorHandler implements KoaMiddlewareInterface {

    constructor(private logger: Logger) {}

    async use(context: any, next: (err?: any) => Promise<any>): Promise<any> {
        try {
            const start = Date.now();
            await next();
            const ms = Date.now() - start;
            console.log('ms is ', ms);
            context.set("Response-Time22", `${ms}ms`);
        } catch (error) {
            console.log('error is222 ', error);
            context.status = error.httpCode || error.status || 500;
            if (Array.isArray(error.errors) && error.errors.every((element: ValidationError) => element instanceof ValidationError)) {// lym ���������֤ģ�Ͷ����sanitizer��ܣ���ÿ�����Խ��м�� 
                let errorMessage = null;
                error.errors.forEach((element: ValidationError) => {
                    Object.keys(element.constraints).forEach((type) => { 
                        errorMessage = element.constraints[type];
                        return false; 
                    });
                    return false;
                });
                context.body = { message: errorMessage };
            } else {
                context.body = { message: error.message };
            }
            if (context.status === 500) {
                this.logger.error(error.message, error);
            } else {
                this.logger.error(error.message);
            }
        }

    }
}

**Comment by martine777** [comment]
sorry, wait a miniute

**Comment by martine777** [comment]
i delete the import lines, the code example is all above

**Comment by martine777** [comment]
const verifyJwt = jwt(appOptions.jwt).unless is no used, please delete it.

**Comment by 19majkel94** [comment]
Ok, looks like the problem is with new versions of koa/koa-router/sth.
I created a new project folder with fresh install of modules and I can reproduce the issue.
However inside our test suite it works ok, there's no 404.

**Comment by martine777** [comment]
i am shamed of my poor english ,execuse me:)

**Comment by 19majkel94** [comment]
Ok, it's more weird - I've bumped the koa deps and still no error in tests.

Here is the reproduce code to clone and npm install:
https://gist.github.com/19majkel94/cbdc281c35bd24f01f219346f5189a8c

@NoNameProvided 
I've pushed enhanced test for this case - f506b182af07e9d3881e7f24fa8ee04b16d582a6.
Can you figure out why this stopped working on newly installed projects?

**Comment by forty6and2** [comment]
Hey all, I can confirm this bug. I tried it with a freshly created project using the code and steps @19majkel94 posted. Here is my package.json. I'm running on Node v8.5.0 on a Lubuntu 16.04.3 machine with ES2017 as my typescript target.

```
{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@types/node": "^8.0.29",
    "ts-node": "^3.3.0",
    "typescript": "^2.5.2"
  },
  "dependencies": {
    "@types/koa": "^2.0.39",
    "@types/koa-bodyparser": "^3.0.25",
    "@types/koa-router": "^7.0.23",
    "koa": "^2.3.0",
    "koa-bodyparser": "^4.2.0",
    "koa-router": "^7.2.1",
    "npx": "^9.6.0",
    "routing-controllers": "^0.7.2"
  }
}
```

**Comment by 19majkel94** [comment]
Sorry guys, looks like [it's fixed](https://github.com/pleerock/routing-controllers/pull/283) and waiting for release `0.7.3`.

**Comment by martine777** [comment]
the issue is not totally settled, i uninstall routing-controller, and install the new "fixed" routing-controllers,when i use both authorizationChecker and middleware,and in controller use promise and setTimeout, it return 404 again!

**Comment by NoNameProvided** [comment]
>  i uninstall routing-controller, and install the new "fixed" routing-controllers

It's not published yet, do you installed from the master branch?

**Comment by pleerock** [comment]
I'll publish it today. Guys please don't forget (and users to update) CHANGELOG as well. New version is here, but changelog is empty

**Comment by martine777** [comment]
i install 0.7.3 version, it works correctly, no 404 emerges ever , thx!

**Comment by 19majkel94** [comment]
Change log is empty because AFAIK they were only bugfixes. Changelog is for more meaningful changes like breaking changes, right? Only custom driver is a new change but useful for 3 peoples in the world 😝 

@pleerock 
We have a project board to keep track of merged and released PR:
https://github.com/pleerock/routing-controllers/projects/3

**Comment by NoNameProvided** [comment]
> Changelog is for more meaningful change

No, actually if should be for bugfixes as well and every change we made, thats why it's called a changelog 😄

**Comment by pleerock** [comment]
Yeah but we can't left versions empty in there. If its only bugs then we need at least write here "fixed bugs #x #y #z"

**Comment by 19majkel94** [comment]
@NoNameProvided @pleerock 
Done in https://github.com/pleerock/routing-controllers/commit/7e5fb34c2cfedbc2f33b6cc3f76818938490505e thanks to the [project board](https://github.com/pleerock/routing-controllers/projects/3) 😄

**Comment by Penggggg** [comment]
@19majkel94 @pleerock Thx guys! Nice to meet Routing-controllers!   : )
