### ISSUE TITLE
Set Cookie

### ISSUE THREAD

**Issue by AndreaPivetta** [pleerock/routing-controllers#298]
What is the right way to set a cookie?
I'd say with something like `@Header("Set-Cookie", "something")` but the value of the cookie is only known at runtime. 
At the moment I'm doing something like:
```
    @Get('/some/:thing')
    getSomeThing
        @Res() res: Response,
        @CookieParam('cookieParam') cookieParam: any,
        @QueryParams() params: any,
        @Param('thing') thing: string) {

        if (!cookieParam && params) {
            res.cookie('cookieParam', this.getCookie(params), {
                expires: new Date(Date.now() + 10 * 60 * 1000),
                path: '/'
            });
        }

        return pug.renderFile(getStaticPath(thing, 'file.pug'));
    }
```

is there a better way?

**Comment by NoNameProvided** [comment]
routing-controller doesn't provide a way for this. Can you confirm @19majkel94? (I am not using the Cookies functionality)

**Comment by 19majkel94** [comment]
I don't use cookies too, but yes, we don't have decorators to support dynamic headers or cookies yet.

**Comment by pangz1** [comment]
can we set headers dynamically now, since this issue was closed one year before?
