### ISSUE TITLE
Session Method Parameter Decorator

### ISSUE THREAD

**Issue by 19majkel94** [pleerock/routing-controllers#30]
Is the `@Session` decorator avaible?
I attach to `req.session` an user object after sucessfull authentication and use it in controler method to check if user is an owner of demanded object from database.
It would be nice to have :

    @Get("/posts")
    getAll(@Session("user") user: User) {
       return postsRepository.getAllByUser(user);
    }

And don't have to parse request object by myself :wink:

**Comment by pleerock** [comment]
No, there is no session decorator yet. I can implement it, but not now, pretty busy with other repositories. Or if someone else can implement it, it would be great, implementation should be easy. For now please use req.session :(

**Comment by 19majkel94** [comment]
If it's all about add Session decorator in `src/decorator/params.ts`, add Session type in `src/metadata/types/ParamTypes.ts` and implement behaviour in `src/ParamHandler.ts` - I think I could do that but first I have to build an app using your stack and then test if the changes will work :smile:

**Comment by pleerock** [comment]
Great! 👍

**Comment by pleerock** [comment]
thanks @19majkel94 . Hope someone take care of it in koa too
