### ISSUE TITLE
some problems with route

### ISSUE THREAD

**Issue by Diluka** [pleerock/routing-controllers#300]
Here is my controller
```ts
@JsonController()
export class IndexController {

    @Get("test")
    test() {
        return "test";
    }

    @Get("/test2")
    test2() {
        return "test2";
    }

    @Get("/test3")
    test3() {
        throw new NotFoundError("test3");
    }
}
```

this is request and response

- `test`
produce an `NotFoundError` with status code `500` and response html (`NotFoundError` should be `404` and ~~`@JsonController` should response `application/json`~~)
p.s. `text/html` is the default content type

- `test2`
This is right. `"test2"`

- `test3`
This is right too. `{"name": "NotFoundError", "message": "test3"}` with `404`

The `test` should act like `test2`. `NotFoundError` may be caused by [here](https://github.com/pleerock/routing-controllers/blob/master/src/metadata/ActionMetadata.ts#L230) join the path without check if it is start with slash `/` or `path` is end with slash `/`. Consider using `path.join` to solve this.
But I'm no clue about why the `Content-Type` is `text/html`.

**UPDATE**
I have an error handler. Enable this status code will be `500`, but I'm using `NotFoundError`
```ts
@Middleware({type: "after", priority: 0})
export class NotFoundMiddleware implements ExpressMiddlewareInterface {

    use(request: any, response: any, next: (err?: any) => any): any {
        if (response.headersSent) return next();
        next(new NotFoundError(`${request.method}:${request.path}`));
    }
}
```

**UPDATE2**
`@Middleware({type: "after", priority: Number.MAX_SAFE_INTEGER})`
`priority` needs to be a large number

**Comment by xujif** [comment]
It is not a bug. without a join ,it can worker with: 
```typescript
@JsonController('/prefix')
export class IndexController {

    @Get("-suffix")
    test() {
        return "suffix";
    }
   
}

```

**Comment by Diluka** [comment]
@xujif OK, this makes sense

```ts
@JsonController()
export class IndexController {
    @Get("test")
    test() {
        return "test";
    }
}
```
But I still wonder what does this represent. 
[base route](https://github.com/pleerock/routing-controllers/blob/master/src/metadata/ActionMetadata.ts#L276) is start with `/`.
`"/" + "test"` should be `/test`, but `/test` is not found

**Comment by Diluka** [comment]
route define can be avoided and there were something wrong with middleware order
