### ISSUE TITLE
@Param does not allow ParamOptions

### ISSUE THREAD

**Issue by IAMtheIAM** [pleerock/routing-controllers#306]
Signature for Param is 

`export declare function Param(name: string): Function;`

But signature for QueryParam is

`export declare function QueryParam(name: string, options?: ParamOptions): Function;`

This is problematic because, by default, in useExpressServer() i have set 
```
    defaults           : {
        paramOptions: {
            required: true // this means that all parameters (@BodyParam, @Param etc in Actions) are required by default
        }
    }
```
so that all params are required. Then I manually override with `@QueryParam("mockData", { required: false }) mockData: boolean`

But Param will not accept the second argument.

Can Param signature be modified to allow ParamOptions like the rest?

**Comment by IAMtheIAM** [comment]
I just noticed [PR ](https://github.com/pleerock/routing-controllers/pull/289). Does that PR solve this issue I mentioned?

**Comment by 19majkel94** [comment]
Nope, just `@Params` and `@QueryParams`

> But Param will not accept the second argument. Can Param signature be modified to allow ParamOptions like the rest?

as it stated:
> params are always required, because if they are missing router will not match the route

**Comment by IAMtheIAM** [comment]
I see. The use case I had was to reduce redundancy in having one route for with route param and one without. Like this:

```
    @Get(route)
    @Get(`${route}/:userName`)
    getOne(
        @QueryParam("bearerToken") bearerToken: string, @QueryParam("mockData", { required: false }) mockData: boolean, @Param("userName", { required: false }) userName: string) {
        if (!bearerToken) {
            return { "message": "Error: Authentication required. Operation not allowed" };
        } else {
            return this._callApi(bearerToken, mockData, userName);
        }
    }
```

That way I don't have to totally duplicate the code just for a route param

**Comment by IAMtheIAM** [comment]
I found a trick. If I set the Param to have a default value of `null` then it works for both routes where there is a route param given, and where there isn't it will just be null
```
    @Get(route)
    @Get(`${route}/:userName`)
    getOne(
        @QueryParam("bearerToken") bearerToken: string, @QueryParam("mockData", { required: false }) mockData: boolean, @Param("userName") userName: string = null) {
        if (!bearerToken) {
            return { "message": "Error: Authentication required. Operation not allowed" };
        } else {
            return this._callApi(bearerToken, mockData, userName);
        }
    }
```
Its really cool how I can put multiple routes for a single method. What do you think about doing it like this?

**Comment by 19majkel94** [comment]
So you call api with undefined?

For me this should be separate routes - one that does not care about userName and the one that use it and return user-specific data.

**Comment by IAMtheIAM** [comment]
OK, yes I ended up making two routes. Thanks for clarification. So a Param aka "RouteParam" should always be required, otherwise make a different route. Got it.

```ts
    @Get(route)
    get(@HeaderParam("Authorization") bearerToken: string,
        @QueryParam("mockData", { required: false }) mockData: boolean) {
            if (!bearerToken) {
                return { "message": "Error: Authentication required. Operation not allowed" };
            } else {
                return this._callApi(bearerToken, mockData);
            }
        }

    // @Get(route)
    @Get(`${route}/:userName`)
    getOne(
        @HeaderParam("Authorization") bearerToken: string,
        @QueryParam("mockData", { required: false }) mockData: boolean,
        @Param("userName") userName: string) {
            if (!bearerToken) {
                return { "message": "Error: Authentication required. Operation not allowed" };
            } else {
                return this._callApi(bearerToken, mockData, userName);
            }
        }
```

**Comment by 19majkel94** [comment]
You should consider moving:
```ts
if (!bearerToken) {
    return { "message": "Error: Authentication required. Operation not allowed" };
} 
```
check into middleware mounted per route or per controller. That will reduce code duplication.
