### ISSUE TITLE
Question: Is there an Optional Authorized decorator?

### ISSUE THREAD

**Issue by BruceHem** [pleerock/routing-controllers#310]
How would u guys solve an endpoint that has an optional authorization (when there's no token or token is incorrect)?

Example:

```js
...
@AuthorizedOptional() // how to do something like this?
async someMethod(@CurrentUser() authUser?: any) {}
...
```

**Comment by xujif** [comment]
your code without @Authorized()  means the auth is an optional authUser will be undefined.
if u want to force auth ,should add @Authorized() and  @CurrentUser({ required: true }).

but this will check token twice in "authorizationChecker" and "currentUserChecker" 
@NoNameProvided 

an other idea is  
@Authorized('optianal')
and return true in authorizationChecker.

**Comment by 19majkel94** [comment]
So you want to achieve that when no token is provided, it will skip authorization checking and `@CurrentUser()` will return `undefined` but when token is provided you want to validate it's roles in `authorizationChecker`? I can't imagine the use case like this 😜 

If you just need to have current user object, don't mark the method as `@Authorized`, just inject `@CurrentUser` into action handler params with `required: false` 😉
