### ISSUE TITLE
regex router not match  with routePrefix

### ISSUE THREAD

**Issue by xujif** [pleerock/routing-controllers#319]
@Get(/pp\/(.*)/)
will match when routePrefix is unset.
bug not match with routePrefix

**Comment by NoNameProvided** [comment]
What is your route prefix and where do you set it?

**Comment by NoNameProvided** [comment]
If your prefix is like `/prefix/` then the generated route will be `/prefix//pp/(.*)/` so you should never add a slash to the end of the prefixes and routes
