### ISSUE TITLE
Including *.ts files in util.DirectoryExportedClassesLoader.importClassesFromDirectories() breaks import

### ISSUE THREAD

**Issue by paistipoikka** [pleerock/routing-controllers#33]
Hi,

`util.DirectoryExportedClassesLoader.importClassesFromDirectories()` includes *ts files. This causes a problem when *.ts files are compiled to *.js files in the same directory. The `importClassesFromDirectories()` function does not know which file to use so it ignores. 

Changing  `formats = [".js", ".ts"]` to `formats = [".js"]` fixes any issues so may be an idea to slightly refactor this. 

Cheers

JT

**Comment by pleerock** [comment]
I recommend you to set another directory for source output for now. Having extra `.ts` format is required because some people use ts-node, which only work with *.ts files. But I know how to fix this, and this gonna be a breaking change. I'll do it later

**Comment by paistipoikka** [comment]
hmmm...ok. 

Not sure if this will all work as I have struggled to get my angular 2 app compiling whilst sharing common model code between the two applications.

**Comment by pleerock** [comment]
try to handle it, if you will have problems let me know, I'll think how to fix your issue

**Comment by pleerock** [comment]
Can you show your configuration? I think its a bit wrong
