### ISSUE TITLE
Promise<void> returns 404

### ISSUE THREAD

**Issue by chaowlert** [pleerock/routing-controllers#35]
Hi,

Thank you for the library. I found one case where behavior might not be correct. For example

```
@Post('/test')    
test() {
    return Promise.resolve();
}
```

Above will return 404 (even above code was run), even I add `EmptyResultCode` also doesn't help.
My expectation is it should return 204.

**Comment by pleerock** [comment]
Looks like a bug. Can you try to use `@UndefinedResultCode` instead?

```typescript
@Post('/test')    
@UndefinedResultCode(204)
test() {
    return Promise.resolve();
}
```

**Comment by chaowlert** [comment]
`UndefinedResultCode` works, thank you, I will use this for interim solution.

Anyway, after test, not only `Promise<void>` returns 404.
`void` also returns 404.

**Comment by 19majkel94** [comment]
Look like `EmptyResultCode` doesn't work at all, I've test it by returning undefined and get 404 instead of demanding http code. But `UndefinedResultCode` works ok.

**Comment by awaragi** [comment]
The empty result worked only when returning an empty array (at least when I have tried couple of months ago)

**Comment by 19majkel94** [comment]
It's weird, source looks ok, so I think that it needs some debugging.
