### ISSUE TITLE
Only `Get` works with Koa

### ISSUE THREAD

**Issue by ss108** [pleerock/routing-controllers#37]
Hi,

I was very happy to come across this project, and tried to switch my Koa 2.0 app to use it. Turns out that any endpoint that is not a GET just hangs and times out.

``` typescript
@JsonController("/api/analytics")
@UseBefore(myAuthMiddleware())
export default class AnalyticsAPIController {
    @Post("/")
    async noworks(){
        return {yes: "hi"};
    }

    @Get("/")
    async works(){
        return {yes: "hi"};
    }
}
```

Here is an example of a controller that works:

``` typescript
@JsonController("/api/clients")
export default class ClientsAPIController {
    @Get("/")
    @UseBefore(myAuthMiddlware())
    async getAll(ctx) : Promise<any[]> {
        let res = await clients.logic.getAll();
        return res;
    }

    @Get("/:clientId")
    async get(@Param("clientId") clientId: number) : Promise<any> {
        let client = await clients.logic.get(clientId);
        return client;
    }
}

```

I'd love to help contribute to this project as well; if you could try to point me in the direction of where you think the error is in the source code, I could take a look/stab.

**Comment by pleerock** [comment]
it should work because there are tests and they all are passing for post and other methods with both express and koa. Also I just checked it with simple example and it seems to work fine. Can you create a minimal example of project with koa, [use this sample](https://github.com/pleerock/routing-controllers/tree/master/sample/sample1-simple-controller) and check if it works?

**Comment by ss108** [comment]
Hmm yes, I created a small project and this code works:

```@JsonController("/api/widgets")
export default class WidgetsAPIController {
    @Get("/:id")
    async get(@Param("id") id: number): Promise<Widget> {
        let all: Widget[] = _getAll();

        let widget: Widget = all.filter((w) => {
            return w.id === id;
        })[0];

        // ctx.body = widget;
        return widget;
    }

    @Post("/")
    async create(ctx) {
        //    ctx.body = ""; 
        return "";
    }
}
```

I don't know what is different aside from the fact that I am not using middlware--but even when I don't use middleware with that other controller, it doesn't work. I will experiment with it a bit.

Also curious as to whether it is possible to access the context in a JsonController--what if I use middleware to store the current user on there, or on ctx.session, and need to access it in a controller action?

**Comment by ss108** [comment]
Ok, so the problem was that I was using the `bodyParser` middleware from koa-better-body globally, and I guess this must have conflicted with the use of koa-body by this library behind the scenes.
