### ISSUE TITLE
Why not declare public with HttpError parameters?

### ISSUE THREAD

**Issue by TonyPythoneer** [pleerock/routing-controllers#43]
Hi @pleerock, I have a question about this.

```
export class HttpError extends Error {
    httpCode: number;
    message: string;

    constructor(httpCode: number, message?: string) {
        super();
        if (httpCode)
            this.httpCode = httpCode;
        if (message)
            this.message = message;

        this.stack = new Error().stack;
    }
}
```

Why not do this?

```
export class HttpError extends Error {

    constructor(public httpCode: number, public message?: string) {
        super();
        this.stack = new Error().stack;
    }
}
```

When it declare `public` with `httpCode` and `message`, it will auto-pass as instance properties.
Perhaps you have special consideration.

**Comment by pleerock** [comment]
nope, I don't have. Maybe I didn't think about it when was doing that... extending Error class is a bit specific thing, and maybe this won't produce same result as what I did, this needs to be checked. If its the same, then your approach should be applied instead

**Comment by TonyPythoneer** [comment]
okay, I am expecting it's the same or not. :smile:
