### ISSUE TITLE
Enabling CORS

### ISSUE THREAD

**Issue by CodingMadeEasy** [pleerock/routing-controllers#46]
I'm having issues enabling CORS. I've tried setting the headers using the @Header decorator

```
@Get('/')
@Render('home')
@Header("Access-Control-Allow-Origin", "*");
@Header("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept");
Index()
{
 //...
}
```

I've tried using the @UseBefore decorator
```
@UseBefore(function(req, res, next) {
    res.header("Access-Control-Allow-Origin", "*");
    res.header("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept");
    next();
})
```

I've tried setting the middleware in the server.ts file

```
expressServer.use(function(req, res, next) {
    res.header("Access-Control-Allow-Origin", "*");
    res.header("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept");
    next();
});
```

Despite trying these 3 methods, I continuously get the error:

> esponse to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost' is therefore not allowed access.

I'm using localhost:80. I've tried on Google Chrome, Firefox, and Microsoft Edge. 

Is there something I'm missing?

**Comment by pleerock** [comment]
Try to use [express cors](https://github.com/expressjs/cors) you simply need to "use" it

**Comment by CodingMadeEasy** [comment]
Thanks for the swift response and I forgot to mention that I used that as well. No headers were added.

**Comment by pleerock** [comment]
hmmm then you have something wrong, I use routing-controllers + express cors and have no problems with it. Maybe you have configured something wrong?

**Comment by pleerock** [comment]
do you import controllers from directory?

**Comment by CodingMadeEasy** [comment]
I import each one separetely.

Ex: 
```
import '../controllers/home';
import '../controllers/test';
```

**Comment by pleerock** [comment]
provide minimal reproduction problem, and I'll try to help

**Comment by CodingMadeEasy** [comment]
Ok give me 10 minutes

**Comment by CodingMadeEasy** [comment]
Server.ts

```
import 'reflect-metadata';
import './homeController';
import * as express from 'express';
import {useExpressServer} from 'routing-controllers';
let cors = require('cors');
let expressServer = express();

expressServer.use(cors());
expressServer.use(express.static('public'));
expressServer.set('view engine', 'vash');
expressServer.set('views', __dirname + '/');
useExpressServer(expressServer);

expressServer.listen(3001, () => console.log('Connected on port 3001'));
```

homeController.ts

```
import {Controller, Get, Render} from "routing-controllers";

@Controller()
export class HomeController
{
    @Get('/')
    @Render('index')
    Index()
    {
    }
}
```

index.vash

```
<html>
    <body>
        <p>This is a test</p>
    </body>
    <script src="app.js"></script>
</html>

```

app.ts

```
var xhr = new XMLHttpRequest();
xhr.onreadystatechange = function()
{
    console.log('test');

    console.log(this.readyState);
    console.log(this.status);

    if (this.readyState == 4 && this.status == 200) {
        // Typical action to be performed when the document is ready:
        console.log(xhr.responseText);
    }
};
xhr.open('GET', 'http://jsonblob.com/api/jsonblob/58084826e4b0bcac9f8207d6', true);
xhr.send();
```

**Comment by CodingMadeEasy** [comment]
@pleerock Did you find anything or notice something unusual about my code?

**Comment by pleerock** [comment]
try to checkout [this branch](https://github.com/pleerock/routing-controllers-express-demo/tree/cors-demo) and test it, it worked on me

**Comment by CodingMadeEasy** [comment]
@pleerock Thanks for the response, I've tried it and it works but this is the opposite of what I'm trying to do. 

In my application, I'm trying to send a GET request to 'http://jsonblob.com/api/jsonblob/58084826e4b0bcac9f8207d6'

And I'm getting a response back saying CORS is not enabled. In the example you sent me, an external website  is trying to request data from your application, whereas in my example, my application is trying to request data from an external website.

**Comment by pleerock** [comment]
> Actually, I believe I completely misunderstood cors. So because I'm trying to make an external request, that external website has to have cors enabled for my url. So jsonblob.com probably doesn't accept cross domain requests from localhost and that's why it's not working?

You are right, if you want to access some other domain you need to setup cors there, not in your server

**Comment by CodingMadeEasy** [comment]
@pleerock Ok thanks. So sorry for wasting your time for a simple misunderstanding. I still need to figure out why the request isn't working though since evidently jsonBlob accepts all requests :/
