### ISSUE TITLE
Bluebird Warning: a promise was created in a handler but was not returned from it

### ISSUE THREAD

**Issue by yura415** [pleerock/routing-controllers#47]
Full text: `Warning: a promise was created in a handler at node_modules/routing-controllers/RoutingControllerExecutor.ts:92:35 but was not returned from it, see http://goo.gl/rRqMUw`

I know that this is not an issue because promise gets handled by another function. But let's make dat bluebird happy. In my opinion proper promise chaining with return statements it's not a code-style adoption.

As a temporary workaround I've had to disable the forgotten return warning:

``` js
Promise.config({
  warnings: {
    wForgottenReturn: false
  }
})
```

**Comment by pleerock** [comment]
what will fix this error? putting return [here](https://github.com/pleerock/routing-controllers/blob/master/src/RoutingControllerExecutor.ts#L94) ?

**Comment by yura415** [comment]
No, putting return there will result in next `catch` block handling errors from action execution. Actually for now it only handles errors from paramsPromises.
You can rewrite this code without recursion using promises API.
I can make a pull-request by Monday with proper promise handling.

**Comment by pleerock** [comment]
I would like not touch recursion method. Any other ways to fix your problem?

**Comment by pleerock** [comment]
looks like something outdated.
