### ISSUE TITLE
Decorators for middleware ?

### ISSUE THREAD

**Issue by ianjohnspain** [pleerock/routing-controllers#5]
Hi

I was wondering if its possible to pass in custom middleware on a route or is it planned ?

or even better, protecting routes using security decorators ? separate library ?

**Comment by pleerock** [comment]
> protecting routes using security decorators ? separate library ?

I have a plans to create such library in perspective, but now I pretty busy with my other open source libraries.

> I was wondering if its possible to pass in custom middleware on a route or is it planned ?

Right now there is no easy way to provide custom middleware, but I believe this is top required feature and Im planning to implement it soon.

**Comment by Salimlou** [comment]
HI @pleerock ,

First off all thank you for this amazing set of libs, great work!!

you will find in [here](https://github.com/MagnusCloudCorp/routing-controllers) an implementation that support Middlewares and a new param decorator for next function.

you can find a example in sample8 directory.

Tell me what you think about it, and if you're ok I will happily create a PR!

Cheers from Morroco

**Comment by pleerock** [comment]
hi @Salimlou . Thank you very much for your contribution. Please create a PR from what you did and lets discuss implementation details there

**Comment by Salimlou** [comment]
PR created #6 , see you on the other side :)

**Comment by pleerock** [comment]
released in 0.6.0
