### ISSUE TITLE
  finalhandler cannot 404 after headers sent +0ms

### ISSUE THREAD

**Issue by MContagious** [pleerock/routing-controllers#50]
After sending response to browser it is throwing following error.
  finalhandler cannot 404 after headers sent +0ms

why it is sending 404 ?

can you tell me why it is throwing error ?

**Comment by pleerock** [comment]
provide a code snippet of what you are doing

**Comment by MContagious** [comment]
Please find the following git repo with reproduceble code.
https://github.com/MContagious/routing-controller-sample

**Comment by pleerock** [comment]
what will happen if you remove `@EmptyResultCode(404)` ?

**Comment by MContagious** [comment]
Initially I dont have that annotation. Later I included to resolve that error but it is still throwing 404 error. But, The browser is getting the json response. Error is written in the server log.

**Comment by pleerock** [comment]
use new `@OnUndefined` / `@OnNull` decorators to resolve this issue.

**Comment by NoNameProvided** [comment]
This happening to me as well. I see this in the console: 

```
  body-parser:json content-type "multipart/form-data; boundary=--------------------------042144984244033328614529" +977ms
  body-parser:json skip parsing +0ms
  morgan log request +977ms
POST /upload/photos 200 - ms - 14
  finalhandler cannot 404 after headers sent +977ms
```

And it also happens when I implicitly return a value:
```ts
@Post('/photos')
  async uploadPhotos() {
    return { wee: 'wooo' };
  }
```

In this case the console output is: 

```
  express:router dispatching POST /upload/photos +34s
  express:router query  : /upload/photos +0ms
  express:router expressInit  : /upload/photos +0ms
  body-parser:json content-type "application/json" +34s
  body-parser:json content-encoding "identity" +0ms
  body-parser:json read body +0ms
  body-parser:json parse body +1ms
  body-parser:json parse json +0ms
  express:router logger  : /upload/photos +1ms
  express:router jsonParser  : /upload/photos +1ms
  body-parser:json body already parsed +1ms
  morgan log request +34s
POST /upload/photos 200 - ms - 34
  finalhandler cannot 404 after headers sent +34s
```

**Comment by pleerock** [comment]
> Probably next() gets called even after a route match?

yes, it is

**Comment by NoNameProvided** [comment]
So is it an easy fix? I think it happens somewhere in the routing-controllers package. Or does it intentional?

**Comment by pleerock** [comment]
> Or is it intentional?

 yes `next()` method call is intentional, because otherwise middleware that execute after your controllers wont work.

**Comment by NoNameProvided** [comment]
Yes, but if I see correctly all we have to do is to register a special last middleware after registering the normal ones not? 

I see you register them in `index.ts` at [here](https://github.com/pleerock/routing-controllers/blob/c263928d08ce3b41f843256f4a3a444d176f86d9/src/index.ts#L191) , isn't it enough to change this to something like

```ts
new RoutingControllers(driver)
        .initialize()
        .registerMiddlewares("before")
        .registerControllers(controllerClasses)
        .registerMiddlewares("after", middlewareClasses); 
        .registerFinalMiddleware(FinalMiddleware);
```

where final middleware looks something like:

```ts
import {ExpressMiddlewareInterface} from "../../src/driver/express/ExpressMiddlewareInterface";
import {Middleware} from "../../src/decorator/Middleware";

@Middleware({ type: "after" })
export class FinalMiddleware implements ExpressMiddlewareInterface {

    use(request: any, response: any, next?: Function): any {
     // next() not called here 
   }
    
}
```

and the `registerFinalMiddleware` function looks something like: 

```
registerFinalMiddleware(class: Function): this {
        this.metadataBuilder
            .buildMiddlewareMetadata([class])
            .forEach(middleware => this.driver.registerMiddleware(middleware));

        return this;
    }
```

**Comment by NoNameProvided** [comment]
Or we can just do 

```ts
new RoutingControllers(driver)
        .initialize()
        .registerMiddlewares("before")
        .registerControllers(controllerClasses)
        .registerMiddlewares("after", [...middlewareClasses, FinalMiddleware]);
```

but then we still have to ensure metadata is already built for this class.

**Comment by NoNameProvided** [comment]
Btw shouldn't we reopen this? Having "Cannot set headers after response is sent" errors for every request is not okay, and I believe using `@OnUndefined` / `@OnNull` doesn't solve the problem, but my proposal does.

**Comment by pleerock** [comment]
> Having "Cannot set headers after response is sent" errors for every request is not okay

right, its not okay. And I don't have such errors after every request. Can you show what are you doing that you have such error?

**Comment by NoNameProvided** [comment]
> As I understood you have such error because of finalhandler you are using, right? If yes, then why are you using it?

`finalhandler ` is a [dependency](https://github.com/expressjs/express/blob/master/package.json#L41) of the express framework itself. It is called as a last middleware to set the status code to`500` if you call `next()` too many times.

On the user side it can be fixed with using a custom middleware:

```ts
import { Middleware, ExpressMiddlewareInterface } from "routing-controllers";
import { NextFunction, Request, Response } from 'express';

const debug = require('debug')('middleware:FinalMiddleware');

@Middleware({ type: "after" })
export class FinalMiddleware implements ExpressMiddlewareInterface {

  use(req: Request, res: Response, next?: NextFunction): any {
    debug('Final middleware reached!')
  }

}
```

and loading it as the last one: 

```ts
this.express = createExpressServer({
      routePrefix: '',
      middlewares: [CorsMiddleware, FinalMiddleware],
    });
```

> This code should not give you such error.

The only cause I can think of is that I am loading some vanilla express middleware this way:

```ts
this.express = createExpressServer({
      routePrefix: '',
      middlewares: [CorsMiddleware, FinalMiddleware],
    });
this.express.use(logger('dev'));
this.express.use(bodyParser.json());
```

But it should still cause the error with the above solution if this would be the root of the error. So I don't have any idea how `finalHandler` get reached. I dont call `next()` anywhere in my code except in `CorsMiddleware` which has the type `before`

**Comment by pleerock** [comment]
There is a `next()` after each route execution, can your issue be because of #114 ?

**Comment by NoNameProvided** [comment]
I don't think so because I have no specific route handlers for OPTION requests, I just early return with a 200 code and an empty response body in the CORS middleware and. I don't call next at all in that case so my routes are not reached.
