### ISSUE TITLE
@UseBefore called before all middlewares

### ISSUE THREAD

**Issue by Iojjj** [pleerock/routing-controllers#55]
Hi @pleerock,

Thanks for your nice lib. I'm trying to run JSON Schema validation for request body using `@UseBefore` decorator. But once my middleware called, I can't retrive `request.body` parameter. Is it an expected behavior?

EmailsController.ts
```javascript
@JsonController("/emails")
export class EmailController {
   
    @Post()
    @UseBefore((request: any, response: any, next: (err?: Error) => void): void => {
        Joi.validate(request.body, schema, (err) => {
            if (err) {
                next(err);
            } else {
                next();
            }
        });
    })
    saveEmail(@Body() email: Email): Email {
        return email;
    }
}
```

index.ts
```javascript
import "es6-shim";
import "reflect-metadata";
import {createExpressServer} from "routing-controllers";

let app = createExpressServer({
    routePrefix: "/api",
    controllers: [__dirname + "/controllers/v1/*.js"]
});
const morgan = require('morgan');
const bodyParser = require('body-parser');
const compress = require('compression');

app
    .use(morgan('dev'))
    .use(compress({}))
    .use(bodyParser.json())
    .use(bodyParser.urlencoded({ extended: true }));
app.listen(3000, () => console.log("started"));
```

If I change `@UseBefore` to `@UseAfter`, request will have a body parameter. How can I get an access to body before `saveEmail` action is called? 

One more question: should `@UseAfter` fail whole request if it returns an error? If I call `next(new Error(...))` there it will log an error but still return a result.

**Comment by pleerock** [comment]
hey, did you fix your issue?

**Comment by Iojjj** [comment]
I've created a composite global middleware that allows to call multiple inner middlewares one by one. This helps to avoid this issue and load middlewares in native for your lib way.

**Comment by montera82** [comment]
@Iojjj posting the final code would have been helpful
