### ISSUE TITLE
Cannot get any data into any Post method

### ISSUE THREAD

**Issue by ldittel** [pleerock/routing-controllers#56]
I have a very simple controller method

`@Post("/register")
    register(@Req() request: any, @Res() response: any) {
console.log(JSON.stringify(request.body));
return "";
     }
`

and I'm trying to pass in some post data using the curl CLI iunder windows:

`curl -X POST -H "Content-Type: application/json" -d "{ \"email\": \"lergfdl@gmail.com\", \"name\": \"john\", \"password\": \"1\" }" localhost:8080/api/auth/register`

Somehow I cannot for the life of me get any of the data to come through i.e. the body is  a l w a y s  empty.
I have absolutely no idea where the problem is as the @Get methods work no problem.

Please advise.
Thansk you so much.

**Comment by ldittel** [comment]
Right, so it turned out to be partially an express.js issue - where the bodyParser needs to be registered in the right order to other middlware e.g. router. I have opted to switch from createExpressServer() to useExpressServer() to have more control of the initialization process. I suspect the createES() method has an issue somewhere.

Anyway, hope it;ll help someone as I was going a little bit mad.

**Comment by 19majkel94** [comment]
Express 4.x is modular so you need to have eg. body-parser and cookie-parser installed and loaded explicitly by yourself. It's not `routing-controllers` fault, it's just how the express behave itself, so I think the issue could be closed now.

**Comment by ldittel** [comment]
That is correct. Thanks for the input.
