### ISSUE TITLE
Gzip compression causes empty responses

### ISSUE THREAD

**Issue by qwert789** [pleerock/routing-controllers#58]
Hi,
I want to use compression module for Gzip compression, here is my server setup:
```
    // use gzip compression
    this.app.use(compression());
    // create expressjs application
    useExpressServer(this.app, {
      routePrefix: '/api/v1',
      controllers: [__dirname + '/controllers/*.js'],
      middlewares: [__dirname + '/middlewares/*.js']
    });
```
My problem is that sometimes i'm getting empty response without the actual data although my controller always returning the data.
Here is my controller code:
```
  @Get()
  public async getAllUsers(@QueryParam("page") page: number = -1 , @QueryParam("count") count: number = -1, @QueryParam("term") term: string = ''): Promise<Page<User>> {
      let result = await this.getUsers(page, count, term);
      return result.data;
  }
```
It's only happens when using with compression module, any thoughts?

**Comment by pleerock** [comment]
sorry for such delayed answer, but if you are still interested in this issue, can you provide a simple repo with reproduction of this problem?

**Comment by pleerock** [comment]
feel free to reopen it if you still have issues.

**Comment by qwert789** [comment]
@pleerock  Works now, thanks!
