### ISSUE TITLE
Flow in returning a promise

### ISSUE THREAD

**Issue by kennyjacob** [pleerock/routing-controllers#61]
What happens in the following code, 
``` javascript
@Post("/session")
@NullResultCode(401)
login( @Body({ required: true }) credentials: Object): Promise<Object> {
    return AuthService.getToken(credentials["username"], credentials["password"]);
}
```
when,

1. Promise rejects
2. Promise resolves

Does 401 occur only if I return null?
Is there a way to specify error message for a 401 using promises?

**Comment by joshualawson** [comment]
I haven't attempted the code above, but you could create a MiddlewareGlobalAfter and check your error status' and change the response that way, you could even just create a Middleware and use the MiddlewareAfter decorator on each method you want to check.

**Comment by ddevcodes** [comment]
I did try this some time ago. It did not return the status code that was set in decorator, so I did this:
```
    @Get("/login")
    login(@Req() req : any, @Res() res : Response) {
        this.log.debug('login()');
        let credentials = auth(req);
        if(credentials){
            return this.userStorage.validateLogin(credentials).then(user => {
                req.user = user;
                req.session.user = user;
                req.session.save();
                return user;
            }).catch(() => {
                res.statusCode = 401;
                return 'Unauthorized';
            });
        }else{
            res.statusCode = 401;
            return 'Unauthorized'
        }
    }
```

**Comment by kennyjacob** [comment]
@joshualawson @ddevcodes these could work for my use case 😃 

In general though, wouldn't it be a hackish way to solve the problem? Aren't we adding extra complexity through  middleware or touching the response objects? 

Would it be fair to have a `@PromiseRejectedResultCode(401)` or something similar where the promise rejects with the error message to be sent in the response body?

**Comment by kennyjacob** [comment]
I tried with `@UndefinedResultCode`, and the results were,
1. Promise rejects with or without a value - 500
2. Promise **resolves without any data** - **401**
3. Promise resolves **with** data - 200 and all is well!

Could someone confirm if this is indeed the behaviour? If yes, the README could use this info. 😄

**Comment by pleerock** [comment]
sorry guys for the delayed answer.

> @NullResultCode(401)
> Does 401 occur only if I return null?

Yes it is.

> Is there a way to specify error message for a 401 using promises?

You can do `throw new UnauthorizedError("your message");` in your code if you want customized messages. Thats quite convenient!

**Comment by pleerock** [comment]
you can also `throw new HttpError(444, "any message!")` where 444 is any http code.
