### ISSUE TITLE
call to router controller direct from client

### ISSUE THREAD

**Issue by yantrab** [pleerock/routing-controllers#66]
hi,
tanks for the awesome  module.

i wonder if its possible to call the controller direct from client side project.

end the controller recognize the caller , and replace the code with "http.get...".
it is possible with decorators?     

i think it woud be grate  for projects that shared the client side with server side

tanks

**Comment by 19majkel94** [comment]
Client side should interact with server side only by REST API.

So you have to decorate the method:
```typescript
@Get("/somepath")
yourmethod(@Req() req, @Res() res) {
    // your logic, like DB access
}
```
And then you just do AJAX call - method GET, path "/somepath", and you return string response or JSON object 😄

**Comment by pleerock** [comment]
I think @19majkel94 gave a great answer. Closing this.
