### ISSUE TITLE
Global middleware usage fails

### ISSUE THREAD

**Issue by szabobar** [pleerock/routing-controllers#67]
Hello,

I am intresting on this project, and I was downloaded your example project (https://github.com/pleerock/routing-controllers-express-demo)

I would like to use Helmet ( https://helmetjs.github.io/ ) with global middleware declaration, but it not works, only works in middleware per-controller, or middleware per-action!

Please check my code:
Working code with middleware per-controller:
`
let helmet = require("helmet");
@UseBefore(helmet())
export class PostController {....}
`
but in main app.ts I would like to use:
`
let helmet = require("helmet");
expressApp.use(helmet());
`

And after I called some URL, then I got this Error:

> Error: Can't set headers after they are sent.
>      at ServerResponse.setHeader (_http_outgoing.js:367:11)
>      at dnsPrefetchControl (E:\workspace\adv\node\routing-controllers-express-demo\node_modules\dns-prefetch-control\index.js:9:11)
>      at call (E:\workspace\adv\node\routing-controllers-express-demo\node_modules\connect\index.js:239:7)
>      at next (E:\workspace\adv\node\routing-controllers-express-demo\node_modules\connect\index.js:183:5)
>      at Function.handle (E:\workspace\adv\node\routing-controllers-express-demo\node_modules\connect\index.js:186:3)
>      at app (E:\workspace\adv\node\routing-controllers-express-demo\node_modules\connect\index.js:51:37)
>      at Layer.handle [as handle_request] (E:\workspace\adv\node\routing-controllers-express-demo\node_modules\express\lib\router\layer.js:95:5)
>      at trim_prefix (E:\workspace\adv\node\routing-controllers-express-demo\node_modules\express\lib\router\index.js:312:13)
>     at E:\workspace\adv\node\routing-controllers-express-demo\node_modules\express\lib\router\index.js:280:7
>      at Function.process_params (E:\workspace\adv\node\routing-controllers-express-demo\node_modules\express\lib\router\index.js:330:12)

Used versions is the lates one in every dependency!

Can you help me what is the problem?

**Comment by 19majkel94** [comment]
Maybe you should use `useExpressApp()` and configure the middleware like in a normal express before?

**Comment by pleerock** [comment]
@szabobar as @19majkel94 said you should configure your express instance and send that to `useExpressApp` and it should solve your problem. Reopen this issue and provide more details if you have problems.

**Comment by zfattuhi** [comment]
Maybe too late to answer the question :), You can just create a routing-controller compatible, like:
`
import helmet from 'helmet';
import { ExpressMiddlewareInterface, Middleware } from 'routing-controllers';

@Middleware({ type: 'before' })
export class HelmetMiddleware implements ExpressMiddlewareInterface {
    public use(request: any, response: any, next?: (err?: any) => any): any {
        return helmet()(request, response, next);
    }
}
`
