### ISSUE TITLE
Session Error - Parameter user_id is required for request

### ISSUE THREAD

**Issue by stonecold123** [pleerock/routing-controllers#69]
Here's my code:
````
@Controller()
export class TestRoutes {
    @Get("/test")
    getTest(@Req() req:Request,@Res() res:Response,@Session("user_id")userId:number) {
        res.send("user:"+userId)
    }
}
````
Is there any way to prevent the request completely dies when "user_id" from the session is undefined?
I'm getting this error 

`Parameter user_id is required for request on GET /test`

when an anonymous visitor visits the page because "user_id" is not defined in the req.session obj. 

I'm not sure if it's related but I have tried custom error handle in your sample and `defaultErrorHandler: false` in `useExpressServer`, but nothing works.

**Comment by 19majkel94** [comment]
The function arguments from `@Session` params are always required, because there is no need to handle request when you want user object e.g. to check privileges but user is not authorized.

If you want to get better error info for this situation instead of "500 parameter is required", you can write a simple auth middleware and use decorator `@UseBefore` on class or method. The default error handler should return nice error code and detailed JSON info.

```typescript
import { Middleware, UnauthorizedError } from "routing-controllers";
import * as express from "express";

/**
 * Authorization middleware for express framework with routing-controllers.
 * Prevent access of not logged user to the routes guarded by this middleware.
 */
@Middleware()
export class AuthorizationMiddleware {

    /**
     * Checks if there is a session in request with atached user.
     * If is, calls next middleware in chain, otherwise throws UnauthorizedError.
     * 
     * @param {express.Request} req The Express request object
     * @param {express.Response} _res The Express response object (not used)
     * @param {express.NextFunction} [next] The next Express middleware function to call after (optional)
     */
    public use(req: express.Request, _res: express.Response, next?: express.NextFunction) {
        if (!req.session || !req.session.user || !req.session.user_id) {
            throw new UnauthorizedError("Access denied, you have to login first!");
        }

        if (next) {
            next();
        }
    }
}
```
