### ISSUE TITLE
Request Interceptor

### ISSUE THREAD

**Issue by programmersharp** [pleerock/routing-controllers#7]
Is it possible to create request interceptor for controller and their actions? My ultimate goal is to add security handler that will check access token.

**Comment by pleerock** [comment]
are you interested in express middleware?

**Comment by programmersharp** [comment]
Yes, I am.

**Comment by pleerock** [comment]
right now you need to directly use express:

    ```typescript
    import * as express from "express";
    import {registerActionsInExpressApp} from "routing-controllers";
    let app = express();
    app.use(........); // HERE YOU USE EXPRESS
    registerActionsInExpressApp(app);
    app.listen(3000);
    ```
More convenient ways of using middlewares is upcoming feature of the next release.
