### ISSUE TITLE
Duplicated info sections in readme

### ISSUE THREAD

**Issue by 19majkel94** [pleerock/routing-controllers#73]
There is small bug in readme - there are two sections about the same feature - creating instances of classes from action params:
- https://github.com/pleerock/routing-controllers#convert-parameters-to-objects
- https://github.com/pleerock/routing-controllers#creating-instances-of-classes-from-action-params

The first one tells you that it's enabled by default and you can disable if you want (which is true) but the second tells about explicit set `useClassTransformer: true` and later explains that it's enabled by default.

I think that there should be one place for merged info about this feature and links to this place in other places.

**Comment by pleerock** [comment]
yes you are right. Are you able to fix it?

**Comment by 19majkel94** [comment]
Of course - should I remove the info from https://github.com/pleerock/routing-controllers#convert-parameters-to-objects and place there the link to https://github.com/pleerock/routing-controllers#creating-instances-of-classes-from-action-params ?

**Comment by pleerock** [comment]
Probably yes.
