### ISSUE TITLE
 Array of int is still treated as array of string

### ISSUE THREAD

**Issue by stonecold123** [pleerock/routing-controllers#79]
I have tried sending this post data to the controller:

````
Content-Type:multipart/form-data; boundary=----WebKitFormBoundary8g8K3OWggVJy11c1

------WebKitFormBoundary8g8K3OWggVJy11c1
Content-Disposition: form-data; name="submit_id[]"

8
------WebKitFormBoundary8g8K3OWggVJy11c1
Content-Disposition: form-data; name="submit_id[]"

9
````

````
    @JsonResponse()
    @Post(`/update`)
    async updateThread(@Session(USER_ID)userId:number,
                       @BodyParam(SUBMIT_ID)submitId:number[],
    ){
       
        console.log(submitId.indexOf(8));  // -1
        console.log(submitId.indexOf('8')); // 0
    }
````
Looking at the console from `phpstorm`, the submitId array is still treated as an array of string. It's quite a problem when `indexOf` is used. Does routing controller have the ability to cast the correct types from multipart/form-data?

**Comment by pleerock** [comment]
no, for arrays type is not casted because its impossible to get known about type of `number[]` in TypeScript because of lack of reflection abilities.
