### ISSUE TITLE
Regression instanceof HttpError(s) after upgrading to 0.6.8+

### ISSUE THREAD

**Issue by awaragi** [pleerock/routing-controllers#85]
All was nice and working great until I attempted to upgrade from 0.6.7 to 0.6.8+. Basically I am unable to instantiate any of the subclasses of HttpError. See couple of failed code and the corresponding error stack trace. Once the instantiation fails, I end up with a 500 error instead of the correct one.

My code is unchanged between 0.6.7 and 0.6.8+

```
    @Get("/:id")
    async retrievesOrganizationByItsId(@Param("id") id: string) {
        let organization = await this.organizationDAO.get(id);
        if (organization) {
            return organization;
        } else {
            throw new NotFoundError("Could not find specified organization with id " + id);
        }
    }
```
{ Error
    at NotFoundError.HttpError [as constructor] (/home/pierre/Developer/Projects/cme-apî/node_modules/routing-controllers/error/http/HttpError.js:18:23)
    at new NotFoundError (/home/pierre/Developer/Projects/cme-apî/node_modules/routing-controllers/error/http/NotFoundError.js:14:28)
    at OrganizationController.<anonymous> (/home/pierre/Developer/Projects/cme-apî/build/app/controllers/organization-controller.js:57:23)
    at next (native)
    at fulfilled (/home/pierre/Developer/Projects/cme-apî/build/app/controllers/organization-controller.js:16:58)
    at process._tickCallback (internal/process/next_tick.js:103:7)
  httpCode: 404,
  name: 'NotFoundError',
  message: 'Could not find specified organization with id 58aef2d59372906cd4fb4561' }
  
  
  
```
import {MiddlewareInterface, Middleware, UnauthorizedError, ForbiddenError, NotFoundError} from "routing-controllers";
/**
 * Base authorization class
 */
class AuthenticatedWithRoles implements MiddlewareInterface {
    @Inject()
    private secureService: SecureService;

    constructor(private agent: boolean, private demandeur: boolean) {
    }

    use(request: any, response: any, next?: (err?: any) => any): any {
        let log = `${request.method}: ${request.path}`;

        // get authorization header
        if (!request.header(AUTHORIZATION)) {
            debug(log, "Missing Authorization header");
            next(new UnauthorizedError());
        } else {
            // no token, done
            let authorization = request.header(AUTHORIZATION);
            if (authorization.startsWith(BEARER && authorization.length > BEARER.length)) {
                debug(log, "Authorization header missing Bearer");
                next(new UnauthorizedError());
  
```
{ Error
    at UnauthorizedError.HttpError [as constructor] (/home/pierre/Developer/Projects/cme-apî/node_modules/routing-controllers/error/http/HttpError.js:18:23)
    at new UnauthorizedError (/home/pierre/Developer/Projects/cme-apî/node_modules/routing-controllers/error/http/UnauthorizedError.js:14:28)
    at AgentOnly.use (/home/pierre/Developer/Projects/cme-apî/build/app/middlewares/authorization-middleware.js:31:18)
    at /home/pierre/Developer/Projects/cme-apî/node_modules/routing-controllers/driver/ExpressDriver.js:312:56
    at Layer.handle [as handle_request] (/home/pierre/Developer/Projects/cme-apî/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/pierre/Developer/Projects/cme-apî/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/home/pierre/Developer/Projects/cme-apî/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/pierre/Developer/Projects/cme-apî/node_modules/express/lib/router/layer.js:95:5)
    at /home/pierre/Developer/Projects/cme-apî/node_modules/express/lib/router/index.js:277:22
    at Function.process_params (/home/pierre/Developer/Projects/cme-apî/node_modules/express/lib/router/index.js:330:12)
    at next (/home/pierre/Developer/Projects/cme-apî/node_modules/express/lib/router/index.js:271:10)
    at cors (/home/pierre/Developer/Projects/cme-apî/node_modules/cors/lib/index.js:179:7)
    at /home/pierre/Developer/Projects/cme-apî/node_modules/cors/lib/index.js:229:17
    at originCallback (/home/pierre/Developer/Projects/cme-apî/node_modules/cors/lib/index.js:218:15)
    at /home/pierre/Developer/Projects/cme-apî/node_modules/cors/lib/index.js:223:13
    at optionsCallback (/home/pierre/Developer/Projects/cme-apî/node_modules/cors/lib/index.js:204:9) httpCode: 401, name: 'UnauthorizedError' }

**Comment by 19majkel94** [comment]
It's weird, all tests for 0.6.10 has been passed... can you create a minimal project with 1 controller with 1 route and just throw `UnauthorizedError` in body? Does it work?

BTW, some protips 😉:
1) Use `const` instead of `let` when you don't modify the variable:
```typescript
const organization = await this.organizationDAO.get(id);
```
2) Use inverted condition to throw error:
```typescript
if (!organization) {
    throw new NotFoundError("Could not find specified organization with id " + id);
}

return organization;
```
It's easier to read and maintain, especially when you have multiple checks and error throwing.

**Comment by awaragi** [comment]
Hi @19majkel94. Thanks for the protips :) how easy is it to forget all the good practices when you change dev language (coming from java for many many years). 

While creating the skeleton projet as you requested. I found that my global error handler is the cause of the issue above.

can you tell me if there is something wrong with this piece of code

```

@MiddlewareGlobalAfter()
export class GlobalErrorHandler implements ErrorMiddlewareInterface {
    error(error: any, request: any, response: any, next: (err?: any) => any): void {
        if(error) {
            debug("Handling error: " + error);
            debug("CastError: " + (error instanceof CastError));
            debug("BadRequestError: " + (error instanceof BadRequestError));
            debug("HttpError: " + (error instanceof HttpError));
        }

        // set http status
        if(error instanceof CastError) {
            let castError = <CastError>error;
            response.status(400); // bad request
        }
        else if (error instanceof BadRequestError) {
            response.status(error.httpCode);
        }
        else if (error instanceof HttpError && error.httpCode) {
            response.status(error.httpCode);
        } else {
            console.error(error);
            response.status(500);
        }
        response.send(Status.failure(error.message));
    }
}
```
 when I run it using 0.6.7 I get
  app Handling error: UnauthorizedError +2ms
  app CastError: false +0ms
  app BadRequestError: false +1ms
  app HttpError: true +0ms


but when I run it using 0.6.10 I get
  app Handling error: UnauthorizedError +1ms
  app CastError: false +2ms
  app BadRequestError: false +0ms
  app HttpError: false +1ms

which leads me to think that something changed in the structure of the errors and instanceof is no longer able to detect the HttpError type??? the result is that my error handler always goes to the generic error 500 instead of handling correctly the various HttpErrors.

**Comment by awaragi** [comment]
okay. I've changed my global error handler not to depend on the type of error and instead just checks if httpCode is available. This resolved the issue but I am still curious on why instanceof fails after upgrading to 0.6.10. From the git logs, I don't see any changes to HttpError.ts file! Any ideas?

**Comment by awaragi** [comment]
```
        // set http status
        if (error instanceof CastError) {
            let castError = <CastError>error;
            response.status(400); // bad request
        } else if (typeof error.httpCode !== "undefined" && error.httpCode) {
            response.status(error.httpCode)
        } else {
            console.error(error);
            response.status(500);
        }

```

**Comment by 19majkel94** [comment]
It's really weird, adding @pleerock 

I've tried sth like this:
```typescript
import { BadRequestError } from 'routing-controllers';

const error = new BadRequestError("Error");
console.log(error instanceof BadRequestError);
console.log(error.constructor);
```
And I got `false`. But the `_proto_` chain looks ok, so I think it's a problem with import/require - when you copy-paste `BadRequestError` and `HttpError` it works ok.

In my project instaceof is working ok, I use 0.6.6 version. I will check what have changed since then but I have no idea what's going on.

**Comment by 19majkel94** [comment]
I have the same issue after accidentally update my project dependencies to routing-controllers@0.6.10 - all my unit tests failed on asserting instance of throwed error. @pleerock what changes to Errors or exports have been made since 0.6.6 release?

**Comment by awaragi** [comment]
Hey Guys, any update on this issue? I've check the logs and see no changes to the source code so it is very weird error.

**Comment by pleerock** [comment]
what exactly is not working? Are you talking about `error instanceof HttpError` ? its not working because of these breaking changes from [typescript](https://github.com/Microsoft/TypeScript/wiki/Breaking-Changes#extending-built-ins-like-error-array-and-map-may-no-longer-work)

**Comment by 19majkel94** [comment]
You're right, I have `target: ES6` in my backend project so copy-paste `BadRequestError` and compile with TS 2.2.1 worked. But I looked at transpiled routing-controller source to ES5 and it's different for 0.6.6 and 0.6.10.

Should we fix creating Error subclasses by calling `Object.setPrototypeOf(this, FooError.prototype);` or it's better to switch to transpile to ES6 with 0.7.0 release? It would be breaking change as it might stops working with older version of node.

**Comment by pleerock** [comment]
> maybe it's time to switch to transpile to ES6 with 0.7.0 release?

we will drop node4 version then. But node4 is important because its lts and used by users. So probably better to do a second fix

> Or we should just fix creating Error subclasses by calling Object.setPrototypeOf(this, FooError.prototype);

this is an easy fix which will make it work

**Comment by 19majkel94** [comment]
This fix might need a version bump to publish it to npm, right?

**Comment by pleerock** [comment]
yes, done in `0.6.11`

**Comment by awaragi** [comment]
Thanks @19majkel94.
