### ISSUE TITLE
Allow extensibility

### ISSUE THREAD

**Issue by shlomiassaf** [pleerock/routing-controllers#88]
Great work! thanks!

I'm trying to use the library for some use cases that are not common, I get blocked and these blocks can be solved quite easily if an extensibility model was possible.

For example, I would like to get a specific value set on the `Request` object, there is no decorator for that. This is specific to my use case, I should be able to create a decorator that does that. Of course the library can't provide all possible decorators.

Another example is a gateway/proxy server that acts as a facade for another server, making complex operations simple. This can be direct mapping (proxy), transforming objects, content aggregation, transactions and a combination of those.

Currently its very hard to write custom decorators since the metadata build process does not expose an api or allow hooking into it.

My proposal is that the library will expose a decorator factory, the factory function will return a decorator that it will manage internally.
The factory will accept an **handler**.

The handler will get invoked on the metadata build process and it will get invoked with the arguments that the decorated was called with as well as the `ClassMetadata` and `ActionMetadata` that were used (or only class metadata for class decorators).

```ts
function handler(metadata: CustomMetadataArgs<Something>) {
}
const MyDecorator = decoratorFactory(handler);
``` 

`CustomMetadataArgs` will hold all needed. 

With this, it's also possible to use `MyDecorator` inside a user decorator for creating a macro aggregator.

```ts
export MyAggregateDecorator(something: any) {
  const myDec = MyDecorator(...);
  return (target: any, key: any) => {
    ... multiple decorators here....
    myDec(target, key);
  };
}
```

**Comment by pleerock** [comment]
Hey. So what you are suggesting is to have machanizm that will allow to easily create decorators that extend routing-controllers functionality. This is already discussed [here](https://github.com/pleerock/routing-controllers/issues/75) and I provided examples how its already possible to do what you want. In the future we are planning to provide a simplified interface to create custom decorators like we did it in [class-validator](https://github.com/pleerock/class-validator#custom-validation-decorators).

**Comment by shlomiassaf** [comment]
@pleerock Thanks

I saw that, problem is I don't get access to ActionMetadata, ClassMetadata etc which are required for things like path calc etc..

**Comment by pleerock** [comment]
I didn't understand whats your problem. What do you mean by `don't get access to x` and `path calc` ? Adding @19majkel94

**Comment by 19majkel94** [comment]
You have access to `Request`, it's all what it's needed for extracting something from request - path, parameters, body, session, locals from middleware, etc. Read the Express.js manual 😜

**Comment by shlomiassaf** [comment]
@19majkel94 not really :)

`ActionMetadata` is a class that has some helpers, for example I wouldn't be able to calculate the full path of an action without it since there is no reference routePrefix anywhere ...

**Comment by 19majkel94** [comment]
As I said - read the Express.js documentation:
```typescript
useExpressServer(app, {
    routePrefix: "/api"
});

@JsonController("/test")
export class TestController {
    @Get("/request/test")
    public test(@Req() req: express.Request): string[] {
        return [
            req.originalUrl,
            req.baseUrl,
            req.url
        ];
    }
}
```
```
[
  "/api/test/request/test",
  "",
  "/api/test/request/test"
]
```
No need to calculate, you have the full path already.

@pleerock 
routing-controllers acts as a middleware - why you don't mount it on path from `routePrefix` using `app.use(routePrefix, ...)`? `routePrefix` should match with `baseUrl`.

**Comment by shlomiassaf** [comment]
@19majkel94 What you said I already know, I suggest you spend more time on reading and understanding the messages rather then assuming people dont know.

I don't want to get it from the request, I want to know it when the app starts...

The library has a bootstrap phase where all controllers/interceptors etc are registered, turning from metadata arguments into actual metadata classes.

The current state is that I can't access the build phase, I don't know when it happens.
In a plugin architecture you need to have hooks/events/phases where you can act on.

Quite simple.

**Comment by pleerock** [comment]
@shlomiassaf sorry for the late response, but I read your messages multiple times and didn't understand all details of the request. Regarding to "custom decorator registration" - there is a [new api](https://github.com/pleerock/routing-controllers/blob/308ade71f8236b1e29ef98d39a1127f61d4616ab/sample/sample14-custom-decorator/UserFromSession.ts) I introduce in next routing-controllers version. What are other requirements of this issue?

**Comment by pleerock** [comment]
feel free to reopen it.
