### ISSUE TITLE
Question: Middleware order

### ISSUE THREAD

**Issue by ssljivic** [pleerock/routing-controllers#92]
Is there a way to control controller/method middleware (UseBefore, UseAfter) execution order?

**Comment by 19majkel94** [comment]
```typescript
export function UseBefore(...middlewares: Array<Function>): Function;
```
Isn't it now the order of middlewares passed to decorator?

**Comment by ssljivic** [comment]
Thanks @19majkel94 ; i don't know what i was thinking :-)
