### ISSUE TITLE
can I use routing-controllers and socket-controllers together in single project?

### ISSUE THREAD

**Issue by xmlking** [pleerock/routing-controllers#95]
I like to use routing-controllers and socket-controllers in my typescript & typedi/ koa project. 
can I mix routing-controllers and socket-controllers in same directory e.g., `/controllers` ?
how do I bootstrap them ? should I use both useKoaServer and useSocketServer?
Do I have to `useContainer` for both JsonController and SocketController  ?

Thanks

**Comment by pleerock** [comment]
Yes you should use useContainer for both. Everything else should be natural. One way is to create express instance and share between them

**Comment by xmlking** [comment]
Want to share my [mixed project](https://github.com/xmlking/hub/tree/master/server) setup, in case someone interested.  Developer experience can be improved with some cosmetic changes  to `socket-controllers` to avoid repeated code.

**Comment by pleerock** [comment]
Closing this. If #106 will be implemented it will make use of both libraries more natural.
