### ISSUE TITLE
Validation error stack trace

### ISSUE THREAD

**Issue by ssljivic** [pleerock/routing-controllers#97]
Whenever a request validation error happens the following stack trace is logged:

```
[ERROR] console - Error
at BadRequestError.HttpError [as constructor] (\node_modules\routing-controllers\error\http\HttpError.js:19:23)
at new BadRequestError (\node_modules\routing-controllers\error\http\BadRequestError.js:14:28)
at \node_modules\routing-controllers\ParamHandler.js:139:45
at process._tickCallback (internal/process/next_tick.js:103:7)
```

Aside from the fact that this stack does not tell much about actual cause of the validation error, it can be very frustrating to have a stack trace logged for each request validation error.

Is there a way to turn this stack trace logging somehow?

Thanks

**Comment by 19majkel94** [comment]
You can create your own error handler middleware :wink:

https://github.com/pleerock/routing-controllers/issues/87#issuecomment-282260085

**Comment by ssljivic** [comment]
Thanks @19majkel94 . I will give it a try.

**Comment by ssljivic** [comment]
@19majkel94 , works like a charm. Thanks.

**Comment by bradyholt** [comment]
I believe you can set `development` option to false to prevent these stack traces.

```
const app = createExpressServer({
    development: false,
    controllers: [...]
});
```

**Comment by pleerock** [comment]
yeah stack trace wont be shown until development is true or NODE_ENV is not prod
