### ISSUE TITLE
can not use other DI container

### ISSUE THREAD

**Issue by neo15201788751** [pleerock/routing-controllers#99]
If I use inversify as DI container,error happend:No matching bindings found for serviceIdentifier: MetadataArgsStorage.

**Comment by pleerock** [comment]
this is inversify-specific issue, I guess you should define `MetadataArgsStorage` it explicitly to inversify container to make it to work.

**Comment by neo15201788751** [comment]
**MetadataArgsStorage** is used by **routing-constroller** scource code:
```
export function defaultMetadataArgsStorage(): MetadataArgsStorage {
    return getFromContainer(MetadataArgsStorage);
}
```
in index.ts line 117-119.
I can not inject it to inversify container.

**Comment by pleerock** [comment]
`getFromContainer` simply calls `container.get` method, just register `MetadataArgsStorage` in inversify before something is called `defaultMetadataArgsStorage` method

**Comment by neo15201788751** [comment]
Thanks,that works.But there are many other issues to be resolved,that is very hard with inversify.
